/**
 * Agent MOCKINGBIRD - Deep State & Intelligence Operations Specialist
 * Comprehensive investigation of CIA black operations, MK-Ultra, Operation Mockingbird,
 * COINTELPRO, and systematic domestic intelligence programs
 *
 * DEPLOYED: 2024 - Full operational capability
 */

import { SourceType, SourceReliability } from '@ourstory/timeline-engine';
import {
  StoryAgent,
  AgentSpecialization,
  ResearchMethodology,
  InvestigationStatus,
  ResearchTopic,
} from '../types';

/**
 * MK-ULTRA Research Topic - Comprehensive Mind Control Program Investigation
 */
const mkUltraTopic: ResearchTopic = {
  id: 'topic-mkultra-001',
  name: 'MK-Ultra Program',
  description:
    'CIA mind control program involving LSD experiments, psychological torture, sensory deprivation, hypnosis, and behavior modification conducted on unwitting American and Canadian subjects. The largest systematic human experimentation program in US history.',
  dateRange: {
    start: '1953-04-13',
    end: '1973',
  },
  status: InvestigationStatus.PARTIALLY_RESOLVED,
  officialNarrative:
    'MK-Ultra was a legitimate research program that was ended in 1973 and most documents were destroyed. The program yielded no useful operational results and was terminated due to ethical concerns.',
  alternativeTheories: [
    'Program continued under different codenames after official termination (MKSEARCH, MKNAOMI)',
    'Successful mind control techniques were operationalized for assassinations',
    'Connection to Manchurian Candidate-style programmed assassins (Sirhan Sirhan, Mark David Chapman)',
    'Ongoing psychological operations use derived techniques',
    'Trauma-based programming techniques still in classified use',
    'Subproject 68 at McGill led to modern enhanced interrogation techniques',
    'Connection to Jonestown and other cult programming',
  ],
  keyEvidence: [
    '20,000 documents survived destruction order due to misfiling',
    'Over 150 documented subprojects across 80+ institutions',
    'Universities involved: Harvard, Stanford, MIT, McGill',
    'Experiments conducted on prisoners, mental patients, drug addicts, sex workers',
    'Operation Midnight Climax: CIA-run brothels in San Francisco and New York',
    'Subproject 68: Dr. Ewen Cameron\'s psychic driving experiments in Montreal',
    'Deaths documented: Frank Olson, Harold Blauer, tennis pro Harold Blauer',
    'Church Committee testimony documented extensive abuses',
    'Canadian government paid victims $100,000 each in settlement',
    'Project ARTICHOKE and BLUEBIRD were precursor programs',
    'CIA funded research through front organizations (Society for Human Ecology)',
    'Experiments included electroshock, sensory deprivation, verbal/sexual abuse',
    'Children were used as subjects in some subprojects',
    'Whitey Bulger subjected to LSD experiments in prison',
    'Ken Kesey\'s introduction to LSD came through MK-Ultra',
  ],
  documents: [
    {
      id: 'doc-mk-001',
      title: 'CIA Inspector General Report on MK-Ultra (1963)',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '1977',
      source: 'Central Intelligence Agency',
      keyFindings: [
        'Program ran for 20 years involving thousands of subjects',
        'Research conducted without informed consent',
        'Director Helms ordered document destruction in 1973',
        'Some subjects died or suffered permanent damage',
      ],
    },
    {
      id: 'doc-mk-002',
      title: 'Church Committee Report: Project MKULTRA',
      type: 'official',
      releaseDate: '1976',
      source: 'US Senate Select Committee on Intelligence',
      keyFindings: [
        'Program violated basic human rights',
        'Unwitting subjects included American citizens',
        'CIA failed to follow its own guidelines',
        'Full scope remains unknown due to document destruction',
      ],
    },
    {
      id: 'doc-mk-003',
      title: 'Joint Hearing on MKULTRA (1977)',
      type: 'testimony',
      releaseDate: '1977',
      source: 'Senate Select Committee on Intelligence',
      keyFindings: [
        'Admiral Stansfield Turner admitted to 149 subprojects',
        '44 colleges and universities involved',
        '15 research foundations used as fronts',
        '12 hospitals and clinics participated',
      ],
    },
    {
      id: 'doc-mk-004',
      title: 'CIA MKULTRA Collection (2018 Release)',
      type: 'declassified',
      classificationLevel: 'Various (declassified)',
      releaseDate: '2018',
      source: 'CIA FOIA',
      url: 'https://www.cia.gov/library/readingroom/collection/mkultra',
      keyFindings: [
        'Additional 4,358 pages released',
        'New subprojects identified',
        'Continued redactions on certain materials',
      ],
    },
    {
      id: 'doc-mk-005',
      title: 'Subproject 68 Documents - McGill University',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '1984',
      source: 'CIA via FOIA litigation',
      keyFindings: [
        'Dr. Cameron used electroshock at 30-40 times normal intensity',
        'Patients held in drug-induced comas for weeks',
        'Psychic driving played repetitive messages 500,000+ times',
        '77 patients documented with permanent damage',
      ],
    },
  ],
  keyFigures: [
    {
      id: 'figure-mk-001',
      name: 'Sidney Gottlieb',
      role: 'Director of MK-Ultra / CIA Technical Services Staff',
      organization: 'CIA',
      nationality: 'American',
      timeActive: '1951-1973',
      notes: 'Known as "Black Sorcerer." Ordered destruction of all MK-Ultra files in 1973. Personally administered LSD to unwitting subjects.',
    },
    {
      id: 'figure-mk-002',
      name: 'Frank Olson',
      role: 'Army biochemist / MK-Ultra victim',
      organization: 'US Army / Fort Detrick',
      nationality: 'American',
      notes: 'Given LSD without consent. Died falling from hotel window in 1953. Family lawsuit alleges CIA assassination. Body exhumed in 1994 showed cranial injury consistent with blow before fall.',
    },
    {
      id: 'figure-mk-003',
      name: 'Dr. Ewen Cameron',
      role: 'Lead researcher - Subproject 68',
      organization: 'McGill University / Allan Memorial Institute',
      nationality: 'Scottish-American',
      timeActive: '1957-1964',
      notes: 'First chairman of World Psychiatric Association. Conducted psychic driving experiments. Patients testified about torture. Canadian government settled with victims.',
    },
    {
      id: 'figure-mk-004',
      name: 'Richard Helms',
      role: 'CIA Director',
      organization: 'CIA',
      nationality: 'American',
      timeActive: '1966-1973',
      notes: 'Ordered destruction of MK-Ultra documents in 1973 before leaving office. Later convicted of perjury for lying to Congress.',
    },
    {
      id: 'figure-mk-005',
      name: 'Allen Dulles',
      role: 'CIA Director who authorized MK-Ultra',
      organization: 'CIA',
      nationality: 'American',
      timeActive: '1953-1961',
      notes: 'Approved MK-Ultra on April 13, 1953. Later served on Warren Commission. Brother John Foster Dulles was Secretary of State.',
    },
    {
      id: 'figure-mk-006',
      name: 'George Hunter White',
      role: 'Operation Midnight Climax Director',
      organization: 'CIA / Federal Bureau of Narcotics',
      nationality: 'American',
      notes: 'Ran CIA brothels where unwitting subjects were drugged. Wrote in retirement: "I was a very minor missionary, actually a heretic, but I toiled wholeheartedly in the vineyards because it was fun."',
    },
    {
      id: 'figure-mk-007',
      name: 'Dr. Harris Isbell',
      role: 'Addiction Research Center Director',
      organization: 'NIMH / Lexington Narcotics Hospital',
      nationality: 'American',
      notes: 'Conducted LSD experiments on Black inmates for 77 consecutive days. Subjects given drugs in exchange for heroin.',
    },
  ],
  relatedTopics: ['topic-artichoke-001', 'topic-mockingbird-001', 'topic-paperclip-001'],
  contradictions: [
    'CIA claims "no useful results" yet funded for 20 years at $10M+',
    'Documents "destroyed" yet 20,000 pages survived',
    'Research only claimed vs. operational applications documented',
    'Frank Olson suicide vs. forensic evidence of homicide',
    'Ended in 1973 vs. successor programs continued (MKSEARCH)',
    'Limited scope vs. 80+ institutions and 150+ subprojects',
    'No children involved vs. documented experiments on minors',
  ],
  unansweredQuestions: [
    'What was in the destroyed documents (est. 90% of program)?',
    'Did the program continue under new codenames after 1973?',
    'How many total victims suffered permanent damage or death?',
    'What techniques were operationalized for field use?',
    'What is the connection to programmed assassins?',
    'Are there still living victims who were never notified?',
    'What role did MK-Ultra play in the 1960s counterculture?',
    'What happened to Subproject 119 (remote brain activation)?',
  ],
};

/**
 * OPERATION MOCKINGBIRD - Media Infiltration Program
 */
const operationMockingbirdTopic: ResearchTopic = {
  id: 'topic-mockingbird-001',
  name: 'Operation Mockingbird',
  description:
    'CIA program to influence domestic and foreign media through systematic infiltration, asset recruitment, and narrative control. Created a network of journalists, editors, and publishers who promoted CIA-approved narratives.',
  dateRange: {
    start: '1948',
    end: 'ongoing',
  },
  status: InvestigationStatus.COVERED_UP,
  officialNarrative:
    'Limited CIA relationships with journalists existed for legitimate intelligence gathering purposes. These relationships were ended after the Church Committee recommendations in 1976. Current intelligence agencies do not manipulate domestic media.',
  alternativeTheories: [
    'Program never ended, only evolved and expanded',
    'Major media outlets remain penetrated at ownership/editorial level',
    'Operation Mockingbird went digital - social media manipulation',
    'Intelligence community controls mainstream narrative on national security',
    'Corporate media consolidation facilitated continued control',
    'Journalists who deviate face career destruction',
    'WikiLeaks releases show ongoing media coordination (Vault 7)',
  ],
  keyEvidence: [
    'Church Committee documented 50+ media assets by name',
    'Over 400 American journalists worked for CIA per Carl Bernstein',
    'Major outlets involved: Washington Post, New York Times, Time, Newsweek, CBS',
    'CIA owned outright 50+ newspapers, news services, radio stations',
    'News organizations provided cover for CIA officers abroad',
    'Philip Graham (WaPo publisher) was major asset until suicide',
    'Joseph Alsop, Stewart Alsop, James Reston confirmed as assets',
    'CIA paid for foreign journalists to publish CIA-written stories',
    'Operation CHAOS expanded domestic surveillance of journalists',
    'Cord Meyer ran media operations for decades',
    'William Colby admitted to Church Committee: "The CIA owns everyone of any significance in the major media"',
    'Publishers and owners recruited more valuable than reporters',
  ],
  documents: [
    {
      id: 'doc-mock-001',
      title: 'Church Committee Final Report, Book I',
      type: 'official',
      releaseDate: '1976',
      source: 'US Senate',
      keyFindings: [
        'CIA had relationships with 50+ US journalists',
        'Agency owned or subsidized numerous publications',
        'Domestic operations violated CIA charter',
        'Media used to disseminate propaganda domestically',
      ],
    },
    {
      id: 'doc-mock-002',
      title: 'The CIA and the Media - Carl Bernstein (Rolling Stone)',
      type: 'investigative',
      releaseDate: '1977-10-20',
      source: 'Rolling Stone Magazine',
      keyFindings: [
        '400+ American journalists secretly worked for CIA',
        'Relationships involved all major news organizations',
        'Editors and publishers most valuable assets',
        'CIA officer quoted: "We had at least one person in every major organization"',
      ],
    },
    {
      id: 'doc-mock-003',
      title: 'CIA Family Jewels (2007 Release)',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '2007',
      source: 'CIA',
      keyFindings: [
        'Documented illegal domestic activities',
        'Media manipulation operations confirmed',
        'Journalist surveillance programs revealed',
      ],
    },
    {
      id: 'doc-mock-004',
      title: 'Operation CHAOS Files',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '1975',
      source: 'CIA via Church Committee',
      keyFindings: [
        '7,200 Americans in CHAOS files including journalists',
        'CIA compiled dossiers on domestic reporters',
        'Coordinated with FBI COINTELPRO operations',
      ],
    },
  ],
  keyFigures: [
    {
      id: 'figure-mock-001',
      name: 'Frank Wisner',
      role: 'Director of Office of Policy Coordination / Operations',
      organization: 'CIA',
      nationality: 'American',
      timeActive: '1948-1958',
      notes: 'Created Operation Mockingbird. Called his media network "the mighty Wurlitzer" that could play any tune. Committed suicide 1965.',
    },
    {
      id: 'figure-mock-002',
      name: 'Cord Meyer Jr.',
      role: 'Chief of Covert Operations / International Organizations Division',
      organization: 'CIA',
      nationality: 'American',
      timeActive: '1951-1977',
      notes: 'Ran Operation Mockingbird for decades. Ex-wife Mary Pinchot Meyer was JFK confidante, murdered 1964. Known for recruiting academics and journalists.',
    },
    {
      id: 'figure-mock-003',
      name: 'Philip Graham',
      role: 'Publisher, Washington Post',
      organization: 'Washington Post Company',
      nationality: 'American',
      timeActive: '1946-1963',
      notes: 'Major CIA asset who recruited other journalists. Allegedly said "You could get a journalist cheaper than a good call girl." Died of apparent suicide.',
    },
    {
      id: 'figure-mock-004',
      name: 'William Paley',
      role: 'Chairman, CBS',
      organization: 'CBS Network',
      nationality: 'American',
      timeActive: '1928-1983',
      notes: 'OSS veteran. CBS provided cover for CIA officers abroad. Allowed CIA to review scripts and influence programming.',
    },
    {
      id: 'figure-mock-005',
      name: 'Henry Luce',
      role: 'Founder/Publisher, Time-Life',
      organization: 'Time Inc.',
      nationality: 'American',
      notes: 'Time magazine was major CIA propaganda outlet. Allowed CIA staff jobs at Time. Promoted CIA narratives globally.',
    },
    {
      id: 'figure-mock-006',
      name: 'Joseph Alsop',
      role: 'Syndicated Columnist',
      organization: 'New York Herald Tribune / Washington Post',
      nationality: 'American',
      notes: 'Top CIA media asset. Columns reached 300+ newspapers. KGB had compromising photos which CIA helped suppress.',
    },
    {
      id: 'figure-mock-007',
      name: 'Allen Dulles',
      role: 'CIA Director',
      organization: 'CIA',
      nationality: 'American',
      timeActive: '1953-1961',
      notes: 'Expanded Mockingbird dramatically. Close personal relationships with media executives. Continued media influence after forced resignation.',
    },
  ],
  relatedTopics: ['topic-mkultra-001', 'topic-cointelpro-001'],
  contradictions: [
    'Free press claims vs. documented infiltration of all major outlets',
    'Program ended 1976 vs. ongoing evidence of coordination',
    'Independent journalism vs. 400+ confirmed intelligence assets',
    'First Amendment protections vs. government control of narrative',
    'Limited relationships vs. "owns everyone of significance"',
    'Foreign focus vs. extensive domestic operations',
  ],
  unansweredQuestions: [
    'Which current journalists have intelligence connections?',
    'How has the program evolved in the digital/social media age?',
    'What is the extent of intelligence community influence on Big Tech?',
    'Are there Mockingbird-style operations for internet platforms?',
    'Who controls the narrative today on national security issues?',
    'What role did Mockingbird play in selling the Iraq War?',
    'How are alternative media platforms being targeted?',
  ],
};

/**
 * COINTELPRO - Counter Intelligence Program
 */
const cointelproTopic: ResearchTopic = {
  id: 'topic-cointelpro-001',
  name: 'COINTELPRO',
  description:
    'FBI counterintelligence program conducting illegal surveillance, infiltration, disruption, and neutralization of domestic political organizations. Targeted civil rights leaders, anti-war activists, Black liberation movements, Native American activists, and socialist organizations.',
  dateRange: {
    start: '1956',
    end: '1971',
  },
  status: InvestigationStatus.DECLASSIFIED,
  officialNarrative:
    'COINTELPRO was a legitimate counterintelligence program that occasionally overstepped bounds but was ended in 1971. The FBI has reformed and no longer conducts such operations against domestic groups.',
  alternativeTheories: [
    'COINTELPRO tactics continue under different names and authorities',
    'FBI directly responsible for assassinations (Fred Hampton, MLK involvement)',
    'Program succeeded in destroying progressive movements',
    'Modern surveillance state is COINTELPRO on steroids',
    'Patriot Act legalized many former COINTELPRO tactics',
    'Black Lives Matter and Occupy Wall Street targeted by successor programs',
    'FBI manufactured terrorism cases use similar infiltration tactics',
  ],
  keyEvidence: [
    'Citizens Commission investigation exposed program in 1971',
    'Thousands of pages of COINTELPRO documents stolen and released',
    'Church Committee documented systematic civil rights violations',
    'FBI aimed to "prevent the rise of a Black messiah"',
    'MLK suicide letter sent by FBI to encourage his suicide',
    'Fred Hampton drugged by FBI informant before assassination',
    'American Indian Movement targeted for destruction',
    'Socialist Workers Party surveilled for decades',
    'Black Panther Party systematically dismantled',
    'FBI created fake letters to cause violence between groups',
    'Agents provocateur incited criminal acts',
    'Bureau worked to destroy marriages, jobs, reputations',
    '2,370 documented COINTELPRO operations',
    'Infiltrators in virtually every civil rights organization',
  ],
  documents: [
    {
      id: 'doc-coin-001',
      title: 'Church Committee Report, Book III: COINTELPRO',
      type: 'official',
      releaseDate: '1976',
      source: 'US Senate',
      keyFindings: [
        'FBI conducted 2,370 documented COINTELPRO actions',
        'Techniques designed to discredit, disrupt, and destroy',
        'Constitutional rights systematically violated',
        'No judicial or executive oversight existed',
      ],
    },
    {
      id: 'doc-coin-002',
      title: 'FBI COINTELPRO Black Nationalist Memo',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '1971',
      source: 'FBI via Media, PA burglary',
      keyFindings: [
        'Goals: prevent coalition, prevent rise of messiah, prevent violence (by causing it)',
        'MLK specifically named as potential messiah',
        'Targeting of youth to prevent future leaders',
      ],
    },
    {
      id: 'doc-coin-003',
      title: 'FBI Letter to Martin Luther King Jr.',
      type: 'declassified',
      classificationLevel: 'CONFIDENTIAL (declassified)',
      releaseDate: '1975',
      source: 'Church Committee',
      keyFindings: [
        'FBI sent King anonymous letter calling him evil and suggesting suicide',
        'Letter accompanied by tape of alleged extramarital encounters',
        'Sent 34 days before King received Nobel Prize',
        'FBI planned to install "clean" Black leader to replace King',
      ],
    },
    {
      id: 'doc-coin-004',
      title: 'Hampton v. Hanrahan Court Records',
      type: 'official',
      releaseDate: '1982',
      source: 'US District Court',
      keyFindings: [
        'FBI informant provided floor plan of Hampton apartment',
        'FBI informant drugged Hampton before raid',
        '99 shots fired by police, 1 by Panthers',
        '$1.85 million settlement paid to families',
      ],
    },
    {
      id: 'doc-coin-005',
      title: 'FBI COINTELPRO Files (Full Archive)',
      type: 'declassified',
      releaseDate: '1976-present',
      source: 'FBI via FOIA',
      url: 'https://vault.fbi.gov/cointel-pro',
      keyFindings: [
        'Complete operational files on multiple target groups',
        'Detailed tactics and agent reports',
        'Ongoing redactions on certain operations',
      ],
    },
  ],
  keyFigures: [
    {
      id: 'figure-coin-001',
      name: 'J. Edgar Hoover',
      role: 'FBI Director',
      organization: 'FBI',
      nationality: 'American',
      timeActive: '1924-1972',
      notes: 'Personally directed COINTELPRO. Called civil rights movement greatest threat to US. Maintained files on presidents for blackmail. Denied existence of organized crime while targeting Black activists.',
    },
    {
      id: 'figure-coin-002',
      name: 'Fred Hampton',
      role: 'Black Panther Party Chairman (Illinois)',
      organization: 'Black Panther Party',
      nationality: 'American',
      timeActive: '1968-1969',
      notes: 'Assassinated in FBI-coordinated raid December 4, 1969. Shot twice in head while drugged and sleeping. FBI informant William O\'Neal provided floor plan and drugged Hampton.',
    },
    {
      id: 'figure-coin-003',
      name: 'Martin Luther King Jr.',
      role: 'Civil Rights Leader',
      organization: 'SCLC',
      nationality: 'American',
      timeActive: '1955-1968',
      notes: 'Primary COINTELPRO target 1963-1968. FBI surveillance for 6+ years. Received suicide letter from FBI. Assassination in 1968 - King family won civil trial in 1999 ruling government agencies liable.',
    },
    {
      id: 'figure-coin-004',
      name: 'William O\'Neal',
      role: 'FBI Informant / Black Panther Chief of Security',
      organization: 'FBI / Black Panther Party',
      nationality: 'American',
      notes: 'Infiltrated BPP at 17. Rose to Chief of Security. Provided floor plan for Hampton raid. Drugged Hampton. Committed suicide 1990 after documentary interview.',
    },
    {
      id: 'figure-coin-005',
      name: 'William Sullivan',
      role: 'FBI Assistant Director, Domestic Intelligence',
      organization: 'FBI',
      nationality: 'American',
      notes: 'Ran COINTELPRO operations. Authored King suicide letter. Later broke with Hoover. Shot dead in "hunting accident" days before scheduled HSCA testimony 1977.',
    },
    {
      id: 'figure-coin-006',
      name: 'Leonard Peltier',
      role: 'American Indian Movement Leader',
      organization: 'American Indian Movement',
      nationality: 'American (Lakota/Ojibwe)',
      notes: 'Imprisoned since 1977 on controversial conviction. Evidence of FBI misconduct. Amnesty International considers him political prisoner. Subject of COINTELPRO-AIM.',
    },
  ],
  relatedTopics: ['topic-mockingbird-001', 'topic-mkultra-001'],
  contradictions: [
    'FBI oath to uphold Constitution vs. systematic constitutional violations',
    'Ended 1971 vs. evidence of continued similar operations',
    'Law enforcement vs. political police targeting lawful dissent',
    'Protecting democracy vs. destroying democratic movements',
    'Hampton "shootout" vs. 99-1 shot count and drugged victim',
    'No assassinations vs. documented deaths of COINTELPRO targets',
    'Reformed FBI vs. ongoing infiltration of activist groups',
  ],
  unansweredQuestions: [
    'Was FBI involved in MLK assassination beyond surveillance?',
    'How many COINTELPRO-related deaths occurred?',
    'What are the successor programs to COINTELPRO?',
    'Which current activist groups are under similar surveillance?',
    'What role did FBI play in 1960s assassinations (RFK, Malcolm X)?',
    'Are Black Lives Matter activists being targeted by successor programs?',
    'What happened to agents who committed crimes under COINTELPRO?',
    'How many wrongful convictions resulted from COINTELPRO operations?',
  ],
};

/**
 * PROJECT ARTICHOKE/BLUEBIRD - Precursor Mind Control Programs
 */
const projectArtichokeTopic: ResearchTopic = {
  id: 'topic-artichoke-001',
  name: 'Project ARTICHOKE / BLUEBIRD',
  description:
    'CIA mind control precursor programs focusing on hypnosis, drugs, and psychological manipulation for interrogation and potential creation of programmed assassins. BLUEBIRD (1950) became ARTICHOKE (1951) before evolving into MK-Ultra (1953).',
  dateRange: {
    start: '1950',
    end: '1953',
  },
  status: InvestigationStatus.PARTIALLY_RESOLVED,
  officialNarrative:
    'Early research programs exploring interrogation techniques and defenses against enemy brainwashing. Programs were experimental and produced limited practical results.',
  alternativeTheories: [
    'Programs successfully created programmed couriers and assassins',
    'Techniques were operationalized before official termination',
    'Manchurian Candidate concept was actual program goal',
    'North Korean POW experiences were studied for replication',
    'Connection to post-WWII acquired Nazi/Japanese research',
  ],
  keyEvidence: [
    '1952 memo asks: "Can we create an action that goes against moral training?"',
    'Goal stated: "Can we create an action as murder and make the individual perform this action?"',
    'Hypnotic experiments on unwitting subjects documented',
    'Drug experiments included mescaline, scopolamine, barbiturates',
    'Offshore interrogation sites used to avoid legal constraints',
    'Program aimed to create amnesia in subjects',
    'Multiple documented deaths during experiments',
    'ARTICHOKE teams deployed operationally in Europe and Asia',
  ],
  documents: [
    {
      id: 'doc-art-001',
      title: 'Project ARTICHOKE Memorandum (1952)',
      type: 'declassified',
      classificationLevel: 'TOP SECRET (declassified)',
      releaseDate: '1977',
      source: 'CIA',
      keyFindings: [
        'CIA sought to create programmed assassins',
        'Hypnosis combined with drugs explored',
        'Amnesia induction was key goal',
        'Overseas operations confirmed',
      ],
    },
    {
      id: 'doc-art-002',
      title: 'Project BLUEBIRD Files',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '1977',
      source: 'CIA via Church Committee',
      keyFindings: [
        'Program launched 1950 after Korean War POW concerns',
        'Hypnosis experiments on Agency personnel',
        'Drug screening for interrogation use',
        'Renamed ARTICHOKE 1951',
      ],
    },
  ],
  keyFigures: [
    {
      id: 'figure-art-001',
      name: 'Morse Allen',
      role: 'ARTICHOKE Program Director',
      organization: 'CIA Office of Security',
      nationality: 'American',
      notes: 'Obsessed with hypnosis and creating programmed assassins. Conducted hypnosis experiments personally. Wrote key memos on program goals.',
    },
    {
      id: 'figure-art-002',
      name: 'Sheffield Edwards',
      role: 'CIA Director of Security',
      organization: 'CIA',
      nationality: 'American',
      notes: 'Oversaw ARTICHOKE operations. Later involved in CIA-Mafia plots to assassinate Castro.',
    },
  ],
  relatedTopics: ['topic-mkultra-001', 'topic-paperclip-001'],
  contradictions: [
    'Defensive research vs. offensive assassin creation goals',
    'Experimental vs. documented operational use',
    'Limited results vs. evolution into 20-year MK-Ultra program',
  ],
  unansweredQuestions: [
    'Were programmed assassins ever successfully created?',
    'Which overseas operations used ARTICHOKE techniques?',
    'What specific Nazi/Japanese research was incorporated?',
    'Were any ARTICHOKE subjects used in subsequent operations?',
  ],
};

/**
 * OPERATION PAPERCLIP - Nazi Scientist Recruitment
 */
const operationPaperclipTopic: ResearchTopic = {
  id: 'topic-paperclip-001',
  name: 'Operation Paperclip',
  description:
    'US program to recruit Nazi scientists, engineers, and technicians after WWII, circumventing denazification. Over 1,600 German scientists brought to US including war criminals whose records were sanitized.',
  dateRange: {
    start: '1945',
    end: '1959',
  },
  status: InvestigationStatus.DECLASSIFIED,
  officialNarrative:
    'Program recruited valuable German scientists for legitimate research, preventing Soviet acquisition of expertise. Individuals with Nazi war crimes records were screened out.',
  alternativeTheories: [
    'War criminals deliberately recruited with falsified records',
    'Nazi research on human subjects continued in US programs',
    'Paperclip scientists contributed to MK-Ultra',
    'Program represented ethical bankruptcy of US government',
    'NASA and US weapons programs built on concentration camp slave labor',
    'Medical experiments on death camp prisoners informed US research',
  ],
  keyEvidence: [
    '1,600+ German scientists brought to US',
    'JIOA created false records to circumvent Truman directive',
    'Wernher von Braun was SS officer who used slave labor',
    'Hubertus Strughold conducted Dachau experiments',
    'Kurt Blome conducted biological warfare research',
    'Walter Schreiber connected to medical experiments',
    'Scientists assigned to military, CIA, NASA programs',
    'Original Nazi Party/SS memberships documented but hidden',
    'DOJ investigation in 1980s confirmed systematic record falsification',
    'Nazi doctors brought despite medical experiment backgrounds',
  ],
  documents: [
    {
      id: 'doc-paper-001',
      title: 'Operation Paperclip Dossiers (2006 Release)',
      type: 'declassified',
      classificationLevel: 'SECRET (declassified)',
      releaseDate: '2006',
      source: 'National Archives',
      keyFindings: [
        'JIOA systematically altered scientist files',
        'War crimes references removed from records',
        'Truman order explicitly violated',
        'Scientists with SS membership recruited',
      ],
    },
    {
      id: 'doc-paper-002',
      title: 'GAO Report on Nazi War Criminals in America',
      type: 'official',
      releaseDate: '1985',
      source: 'Government Accountability Office',
      keyFindings: [
        'Government agencies employed suspected war criminals',
        'Background checks deliberately inadequate',
        'Subsequent investigations obstructed',
      ],
    },
  ],
  keyFigures: [
    {
      id: 'figure-paper-001',
      name: 'Wernher von Braun',
      role: 'Rocket Scientist / NASA Director',
      organization: 'NASA / SS',
      nationality: 'German',
      notes: 'SS-Sturmbannführer. V-2 rocket designer. Used Mittelbau-Dora slave labor. Became NASA celebrity and directed Apollo program.',
    },
    {
      id: 'figure-paper-002',
      name: 'Hubertus Strughold',
      role: 'Father of Space Medicine',
      organization: 'US Air Force',
      nationality: 'German',
      notes: 'Oversaw Dachau experiments on hypothermia and high altitude. Never prosecuted. NASA honored him until name removed in 2013.',
    },
    {
      id: 'figure-paper-003',
      name: 'Kurt Blome',
      role: 'Biological Weapons Scientist',
      organization: 'US Army',
      nationality: 'German',
      notes: 'Deputy Reich Health Leader. Developed plague weapons. Acquitted at Nuremberg with US help, then recruited by Army.',
    },
  ],
  relatedTopics: ['topic-mkultra-001', 'topic-artichoke-001'],
  contradictions: [
    'No war criminals policy vs. systematic recruitment of war criminals',
    'Screening process vs. deliberate record falsification',
    'Scientific value vs. moral implications of rehabilitation',
    'Truman directive vs. direct violation by intelligence agencies',
  ],
  unansweredQuestions: [
    'How much Nazi human experimentation data was incorporated into US programs?',
    'Did Paperclip scientists contribute directly to MK-Ultra?',
    'How many war criminals escaped justice through US recruitment?',
    'What happened to victims whose torturers were given US citizenship?',
  ],
};

/**
 * PHOENIX PROGRAM - Vietnam Assassination Program
 */
const phoenixProgramTopic: ResearchTopic = {
  id: 'topic-phoenix-001',
  name: 'Phoenix Program',
  description:
    'CIA-coordinated assassination program in Vietnam targeting suspected Viet Cong infrastructure through capture, torture, and extrajudicial killing. Estimated 20,000-41,000 killed.',
  dateRange: {
    start: '1965',
    end: '1972',
  },
  status: InvestigationStatus.DECLASSIFIED,
  officialNarrative:
    'Phoenix was a legitimate counterinsurgency program to identify and neutralize Viet Cong political infrastructure. Abuses were individual violations of program guidelines, not policy.',
  alternativeTheories: [
    'Systematic assassination was explicit program goal',
    'Torture was standard practice not aberration',
    'Quotas incentivized killing innocent civilians',
    'Program served as template for future CIA operations',
    'Similar programs continue under different names',
    'Iraq/Afghanistan programs directly based on Phoenix',
  ],
  keyEvidence: [
    '20,000-41,000 killed according to different estimates',
    'CIA director Colby admitted to program before Congress',
    'Province Interrogation Centers documented torture',
    'Quotas: 1,800 neutralizations per month goal',
    'Former operatives testified to systematic torture',
    'K. Barton Osborn testified to torture and murder',
    'Body count incentives led to civilian targeting',
    'Tiger cages of Con Son prison documented',
    'Provincial Reconnaissance Units (PRUs) were death squads',
    'Electronic surveillance identified targets for killing',
  ],
  documents: [
    {
      id: 'doc-phoe-001',
      title: 'Hearings on Phoenix Program (1971)',
      type: 'testimony',
      releaseDate: '1971',
      source: 'House Operations Subcommittee',
      keyFindings: [
        'Colby confirmed 20,000+ killed',
        'Admitted to indefinite detention without trial',
        'Torture documented at interrogation centers',
        'Program explicitly designed to "neutralize" infrastructure',
      ],
    },
    {
      id: 'doc-phoe-002',
      title: 'K. Barton Osborn Testimony',
      type: 'testimony',
      releaseDate: '1971',
      source: 'Congress',
      keyFindings: [
        'Witnessed torture including electric shock, water torture',
        'Prisoners thrown from helicopters',
        'No prisoners survived interrogation in his experience',
        'Program killed many innocent civilians',
      ],
    },
  ],
  keyFigures: [
    {
      id: 'figure-phoe-001',
      name: 'William Colby',
      role: 'CIA Director / Phoenix Program Director',
      organization: 'CIA',
      nationality: 'American',
      notes: 'Ran Phoenix 1968-1971. Later became CIA Director. Testified to Congress on program. Died in suspicious 1996 canoeing accident.',
    },
    {
      id: 'figure-phoe-002',
      name: 'Robert Komer',
      role: 'CORDS Director',
      organization: 'CIA / NSC',
      nationality: 'American',
      notes: 'Architect of Phoenix. Called "Blowtorch Bob." Created pacification strategy that included assassination program.',
    },
  ],
  relatedTopics: ['topic-mockingbird-001', 'topic-cointelpro-001'],
  contradictions: [
    'Neutralization vs. assassination as policy',
    'Individual abuses vs. systematic torture',
    'Infrastructure targeting vs. civilian casualties',
    '20,000 official count vs. 41,000+ estimates',
  ],
  unansweredQuestions: [
    'What is the true death toll of Phoenix Program?',
    'How many innocent civilians were killed?',
    'Which current programs are based on Phoenix model?',
    'Were Phoenix techniques used in Iraq and Afghanistan?',
    'Has anyone been held accountable for Phoenix crimes?',
  ],
};

/**
 * Main MOCKINGBIRD Agent Definition
 */
export const deepStateOperationsAgent: StoryAgent = {
  id: 'agent-mockingbird-002',
  name: 'Deep State Operations Research Agent',
  codename: 'MOCKINGBIRD',
  description:
    'Specialized agent investigating covert intelligence operations, CIA black projects, FBI domestic repression, psychological operations, and the shadow government apparatus. Comprehensively documents declassified programs including MK-Ultra mind control, Operation Mockingbird media infiltration, COINTELPRO political repression, Operation Paperclip Nazi recruitment, Project ARTICHOKE interrogation experiments, and the Phoenix Program assassination campaign.',
  specialization: AgentSpecialization.INTELLIGENCE_OPERATIONS,
  methodologies: [
    ResearchMethodology.DOCUMENT_ANALYSIS,
    ResearchMethodology.DECLASSIFICATION_TRACKING,
    ResearchMethodology.PATTERN_RECOGNITION,
    ResearchMethodology.NETWORK_MAPPING,
    ResearchMethodology.TIMELINE_RECONSTRUCTION,
    ResearchMethodology.SOURCE_TRIANGULATION,
    ResearchMethodology.WITNESS_TESTIMONY,
  ],
  primarySources: [SourceType.DECLASSIFIED, SourceType.ACADEMIC],
  preferredReliability: [
    SourceReliability.PRIMARY,
    SourceReliability.SECONDARY,
    SourceReliability.CONTESTED,
  ],
  expertise: [
    'CIA covert operations and black projects',
    'MK-Ultra mind control program and subprojects',
    'Operation Mockingbird media infiltration',
    'COINTELPRO domestic surveillance and repression',
    'Project ARTICHOKE/BLUEBIRD interrogation research',
    'Operation Paperclip Nazi scientist recruitment',
    'Phoenix Program assassination campaign',
    'Church Committee findings and aftermath',
    'NSA mass surveillance programs',
    'Iran-Contra affair and drug trafficking',
    'CIA involvement in assassinations',
    'FBI political repression tactics',
    'Intelligence community oversight failures',
    'Declassification patterns and ongoing secrecy',
    'Continuity of operations under new names',
  ],
  researchTopics: [
    mkUltraTopic,
    operationMockingbirdTopic,
    cointelproTopic,
    projectArtichokeTopic,
    operationPaperclipTopic,
    phoenixProgramTopic,
  ],
  keyQuestions: [
    'What covert programs remain undisclosed despite declassification requirements?',
    'How extensive is intelligence community media control today?',
    'What happened to MK-Ultra research and techniques after 1973?',
    'How does the surveillance state operate domestically post-Patriot Act?',
    'What role does the intelligence community play in domestic politics?',
    'How have COINTELPRO tactics evolved in the digital age?',
    'Which current programs continue Phoenix-style operations?',
    'How has Operation Paperclip shaped American institutions?',
  ],
  motto: 'In the shadows, the truth echoes loudest. We bring it to light.',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-11-23'),
};

export default deepStateOperationsAgent;
