/**
 * Agent ROTHSCHILD - Financial Systems & Banking Research Specialist
 * Investigates central banking, monetary manipulation, and financial control mechanisms
 */

import { SourceType, SourceReliability } from '@ourstory/timeline-engine';
import {
  StoryAgent,
  AgentSpecialization,
  ResearchMethodology,
  InvestigationStatus,
} from '../types';

export const financialSystemsAgent: StoryAgent = {
  id: 'agent-rothschild-003',
  name: 'Financial Systems Research Agent',
  codename: 'ROTHSCHILD',
  description:
    'Specialized agent investigating the hidden history of central banking, the Federal Reserve System, international banking cartels, and mechanisms of financial control. Analyzes the connection between monetary policy, political power, and wealth concentration.',
  specialization: AgentSpecialization.FINANCIAL_SYSTEMS,
  methodologies: [
    ResearchMethodology.DOCUMENT_ANALYSIS,
    ResearchMethodology.PATTERN_RECOGNITION,
    ResearchMethodology.NETWORK_MAPPING,
    ResearchMethodology.TIMELINE_RECONSTRUCTION,
    ResearchMethodology.SOURCE_TRIANGULATION,
  ],
  primarySources: [SourceType.ACADEMIC, SourceType.DECLASSIFIED, SourceType.ALTERNATIVE],
  preferredReliability: [
    SourceReliability.PRIMARY,
    SourceReliability.SECONDARY,
    SourceReliability.CONTESTED,
  ],
  expertise: [
    'Federal Reserve System creation',
    'Jekyll Island meeting (1910)',
    'Central banking history',
    'Bank for International Settlements (BIS)',
    'Basel Accords and banking regulations',
    'Central Bank Digital Currencies (CBDCs)',
    'Bretton Woods system',
    'Nixon Shock (1971)',
    'Gold standard history',
    'Petrodollar system',
    'Quantitative easing',
    'Rothschild banking dynasty',
    'International banking families',
    '2008 Financial Crisis',
    'Too Big To Fail banks',
    'Financial crisis engineering',
    'Fiat currency mechanics',
    'Government debt monetization',
  ],
  researchTopics: [
    {
      id: 'topic-fed-001',
      name: 'Federal Reserve Creation',
      description:
        'Investigation into the secret meeting at Jekyll Island and the creation of the Federal Reserve System in 1913.',
      dateRange: {
        start: '1910-11-22',
        end: '1913-12-23',
      },
      status: InvestigationStatus.PARTIALLY_RESOLVED,
      officialNarrative:
        'The Federal Reserve was created by Congress to provide a stable monetary system and prevent banking panics after the 1907 crisis.',
      alternativeTheories: [
        'Private banking cartel seized control of US monetary policy',
        'Jekyll Island meeting was conspiracy to create banking monopoly',
        'Federal Reserve is neither federal nor has reserves',
        'System designed to enable perpetual debt and inflation',
        'Connected to broader international banking network',
      ],
      keyEvidence: [
        'Secret Jekyll Island meeting documented by participant',
        'Attendees represented 1/4 of world wealth',
        'Bill drafted in secret, passed during holiday recess',
        'Federal Reserve is privately owned',
        'No full audit ever conducted',
        'Congressman McFadden impeachment attempts',
      ],
      documents: [
        {
          id: 'doc-fed-001',
          title: 'The Creature from Jekyll Island',
          type: 'investigative',
          source: 'G. Edward Griffin',
          keyFindings: [
            'Detailed account of secret meeting',
            'Banking cartel structure documented',
            'Monetary manipulation mechanisms explained',
          ],
        },
        {
          id: 'doc-fed-002',
          title: 'Congressional Record - McFadden Speech',
          type: 'official',
          releaseDate: '1934',
          source: 'US Congress',
          keyFindings: [
            'Federal Reserve accused of deliberate deflation',
            'International banking connections alleged',
            'Called for abolition of Fed',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-fed-001',
          name: 'Paul Warburg',
          role: 'Federal Reserve architect',
          organization: 'Kuhn, Loeb & Co.',
          nationality: 'German-American',
          notes: 'Primary author of Federal Reserve Act; brother headed German central bank',
        },
        {
          id: 'figure-fed-002',
          name: 'J.P. Morgan',
          role: 'Banker',
          organization: 'J.P. Morgan & Co.',
          nationality: 'American',
          notes: 'Key player in Jekyll Island meeting; orchestrated 1907 panic',
        },
        {
          id: 'figure-fed-003',
          name: 'Nelson Aldrich',
          role: 'Senator',
          organization: 'US Senate',
          nationality: 'American',
          notes: 'Rockefeller relative; sponsored Federal Reserve legislation',
        },
      ],
      relatedTopics: ['topic-bis-001', 'topic-petrodollar-001'],
      contradictions: [
        'Public institution vs. private ownership',
        'Stability mandate vs. boom-bust cycles',
        'Transparency claims vs. no full audit',
        'Democratic control vs. unelected governors',
      ],
      unansweredQuestions: [
        'Who truly owns the Federal Reserve?',
        'What would a full audit reveal?',
        'How coordinated are central bank policies globally?',
        'What is the endgame of perpetual debt expansion?',
      ],
    },
    {
      id: 'topic-petrodollar-001',
      name: 'Petrodollar System',
      description:
        'Investigation into the agreement between the US and Saudi Arabia to price oil exclusively in dollars.',
      dateRange: {
        start: '1974',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'Natural market evolution led to dollar-denominated oil trading due to US economic dominance.',
      alternativeTheories: [
        'Secret agreement ensures dollar hegemony',
        'Military protection for Saudi Arabia in exchange',
        'Countries abandoning petrodollar face regime change',
        'Iraq, Libya invaded after threatening dollar status',
        'System enables unlimited US deficit spending',
      ],
      keyEvidence: [
        'Kissinger-Saudi negotiations documented',
        'Iraq switched to euros before invasion',
        'Libya proposed gold dinar before intervention',
        'Iran oil bourse threatens dollar',
        'Saudi Arabia largest buyer of US weapons',
      ],
      documents: [
        {
          id: 'doc-petro-001',
          title: 'Declassified State Department Cables',
          type: 'declassified',
          source: 'US State Department',
          keyFindings: [
            'Negotiations between Kissinger and Saudi royals',
            'Oil pricing agreement details',
            'Military cooperation terms',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-petro-001',
          name: 'Henry Kissinger',
          role: 'Secretary of State',
          organization: 'US State Department',
          nationality: 'American',
          notes: 'Negotiated petrodollar agreement with Saudi Arabia',
        },
      ],
      relatedTopics: ['topic-fed-001'],
      contradictions: [
        'Free market vs. enforced dollar pricing',
        'Democracy promotion vs. Saudi alliance',
        'Liberation wars vs. petrodollar enforcement',
      ],
      unansweredQuestions: [
        'What happens when petrodollar system ends?',
        'How many wars were fought for dollar hegemony?',
        'What are the terms of the Saudi agreement?',
      ],
    },
    {
      id: 'topic-bis-001',
      name: 'Bank for International Settlements',
      description:
        'Investigation into the BIS - the central bank of central banks - and its role in coordinating global monetary policy outside democratic oversight.',
      dateRange: {
        start: '1930-05-17',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'The BIS was created to manage German reparation payments and evolved into a forum for central bank cooperation to ensure monetary and financial stability.',
      alternativeTheories: [
        'BIS serves as shadow world government for finance',
        'Created to facilitate transfers between warring nations',
        'Operated with Nazi Germany throughout WWII',
        'Immune from all national laws and oversight',
        'Coordinates currency manipulation globally',
        'Testing ground for central bank digital currencies (CBDCs)',
      ],
      keyEvidence: [
        'BIS founding charter grants complete immunity',
        'Continued operations during WWII with Nazi gold',
        'No democratic accountability to any nation',
        'Secret meetings of central bank governors',
        'Basel Accords reshape global banking regulations',
        'CBDC coordination through BIS Innovation Hub',
      ],
      documents: [
        {
          id: 'doc-bis-001',
          title: 'Tower of Basel',
          type: 'investigative',
          source: 'Adam LeBor',
          keyFindings: [
            'BIS Nazi gold transfer history documented',
            'Complete legal immunity explained',
            'Central bank coordination mechanisms revealed',
          ],
        },
        {
          id: 'doc-bis-002',
          title: 'BIS Annual Reports',
          type: 'official',
          source: 'Bank for International Settlements',
          keyFindings: [
            'Global monetary policy coordination',
            'CBDC development progress',
            'Cross-border payment initiatives',
          ],
        },
        {
          id: 'doc-bis-003',
          title: 'Morgenthau Diaries - BIS Investigation',
          type: 'declassified',
          releaseDate: '1965',
          source: 'US Treasury Department',
          keyFindings: [
            'Treasury Secretary sought BIS dissolution',
            'Nazi collaboration evidence documented',
            'Post-war decision to preserve BIS',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-bis-001',
          name: 'Montagu Norman',
          role: 'BIS Co-Founder',
          organization: 'Bank of England',
          nationality: 'British',
          notes: 'Bank of England Governor; advocated BIS creation; maintained German banking relationships during war',
        },
        {
          id: 'figure-bis-002',
          name: 'Hjalmar Schacht',
          role: 'BIS Board Member',
          organization: 'Reichsbank',
          nationality: 'German',
          notes: 'Nazi Finance Minister; BIS director; facilitated Nazi rearmament financing',
        },
        {
          id: 'figure-bis-003',
          name: 'Agustín Carstens',
          role: 'General Manager',
          organization: 'Bank for International Settlements',
          nationality: 'Mexican',
          notes: 'Current BIS head; leading CBDC implementation globally',
        },
      ],
      relatedTopics: ['topic-fed-001', 'topic-nixon-001', 'topic-cbdc-001'],
      contradictions: [
        'Financial stability mandate vs. repeated crises',
        'Neutral institution vs. wartime Nazi dealings',
        'International cooperation vs. unaccountable power',
        'Public institution vs. private central bank ownership',
      ],
      unansweredQuestions: [
        'What is discussed in secret Basel meetings?',
        'How much Nazi gold passed through BIS?',
        'What is the true CBDC implementation timeline?',
        'How are Basel regulations designed to benefit large banks?',
      ],
    },
    {
      id: 'topic-nixon-001',
      name: 'Nixon Shock - End of Gold Standard',
      description:
        'Investigation into the 1971 decision to end dollar-gold convertibility and its transformation of the global monetary system.',
      dateRange: {
        start: '1971-08-15',
        end: '1973-03-19',
      },
      status: InvestigationStatus.PARTIALLY_RESOLVED,
      officialNarrative:
        'Nixon temporarily suspended gold convertibility to combat speculators and protect American economic interests. The subsequent floating exchange rate system proved more flexible.',
      alternativeTheories: [
        'Deliberate destruction of monetary discipline',
        'Enabled unlimited money printing and debt',
        'Planned transition to pure fiat system',
        'Connected to Vietnam War financing needs',
        'Shifted wealth from savers to debtors',
        'French gold demands triggered crisis',
      ],
      keyEvidence: [
        'No Congressional approval sought',
        'Announced on Sunday evening to prevent market reaction',
        'Temporary measure became permanent',
        'US gold reserves depleted by foreign redemptions',
        'Dollar has lost 98% purchasing power since 1971',
        'All currencies became fiat simultaneously',
      ],
      documents: [
        {
          id: 'doc-nixon-001',
          title: 'Nixon Address to the Nation - August 15, 1971',
          type: 'official',
          source: 'White House Archives',
          keyFindings: [
            'Announced as temporary measure',
            'Blamed speculators for crisis',
            'No mention of permanent fiat transition',
          ],
        },
        {
          id: 'doc-nixon-002',
          title: 'Camp David Meeting Transcripts',
          type: 'declassified',
          releaseDate: '2001',
          source: 'Nixon Presidential Library',
          keyFindings: [
            'Connally pushed for aggressive approach',
            'Volcker warned of consequences',
            'Decision made in secret weekend meeting',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-nixon-001',
          name: 'Richard Nixon',
          role: 'President',
          organization: 'US Government',
          nationality: 'American',
          notes: 'Made decision without Congressional approval; called it temporary',
        },
        {
          id: 'figure-nixon-002',
          name: 'John Connally',
          role: 'Treasury Secretary',
          organization: 'US Treasury',
          nationality: 'American',
          notes: 'Architect of Nixon Shock; famous quote: "The dollar is our currency but your problem"',
        },
        {
          id: 'figure-nixon-003',
          name: 'Paul Volcker',
          role: 'Undersecretary for Monetary Affairs',
          organization: 'US Treasury',
          nationality: 'American',
          notes: 'Participated in Camp David meeting; later Fed Chair during 1980s rate crisis',
        },
        {
          id: 'figure-nixon-004',
          name: 'Charles de Gaulle',
          role: 'President of France',
          organization: 'French Government',
          nationality: 'French',
          notes: 'Demanded gold for dollars; called US privilege "exorbitant"',
        },
      ],
      relatedTopics: ['topic-fed-001', 'topic-petrodollar-001', 'topic-bis-001'],
      contradictions: [
        'Temporary measure vs. permanent change',
        'Protecting economy vs. enabling inflation',
        'Market stability vs. currency chaos',
        'Democratic process vs. unilateral action',
      ],
      unansweredQuestions: [
        'Was the transition to fiat planned in advance?',
        'What role did Vietnam War costs play?',
        'Why was no return to gold ever attempted?',
        'How much gold actually remained in Fort Knox?',
      ],
    },
    {
      id: 'topic-2008-001',
      name: '2008 Financial Crisis Engineering',
      description:
        'Investigation into the 2008 financial crisis, bailout mechanisms, and consolidation of banking power.',
      dateRange: {
        start: '2007-08-01',
        end: '2010-07-21',
      },
      status: InvestigationStatus.PARTIALLY_RESOLVED,
      officialNarrative:
        'A housing bubble fueled by subprime mortgages led to a financial crisis requiring emergency government intervention to prevent economic collapse.',
      alternativeTheories: [
        'Crisis deliberately engineered for consolidation',
        'Bailouts designed to save banks not homeowners',
        'Goldman Sachs captured Treasury Department',
        'Controlled demolition of competitors',
        'Massive wealth transfer from public to private',
        'No accountability to prevent future crises',
      ],
      keyEvidence: [
        'Goldman Sachs bet against products they sold',
        'Paulson (ex-Goldman CEO) designed bailout',
        'Too Big To Fail banks became bigger',
        'Bear Stearns and Lehman selectively destroyed',
        'AIG bailout funneled money to Goldman',
        'Exposed Fed secret $16 trillion in loans',
        'Zero executives prosecuted',
      ],
      documents: [
        {
          id: 'doc-2008-001',
          title: 'Financial Crisis Inquiry Commission Report',
          type: 'official',
          releaseDate: '2011',
          source: 'US Government',
          keyFindings: [
            'Crisis was avoidable',
            'Widespread failures in regulation',
            'Systemic breakdown in accountability',
          ],
        },
        {
          id: 'doc-2008-002',
          title: 'GAO Audit of Federal Reserve',
          type: 'official',
          releaseDate: '2011',
          source: 'Government Accountability Office',
          keyFindings: [
            '$16.1 trillion in secret loans revealed',
            'Conflicts of interest documented',
            'Foreign bank recipients identified',
          ],
        },
        {
          id: 'doc-2008-003',
          title: 'Senate Permanent Subcommittee Investigation - Goldman Sachs',
          type: 'official',
          releaseDate: '2011',
          source: 'US Senate',
          keyFindings: [
            'Goldman sold products they internally called "junk"',
            'Bet against clients positions',
            'Misled Congress about practices',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-2008-001',
          name: 'Henry Paulson',
          role: 'Treasury Secretary',
          organization: 'US Treasury / Goldman Sachs',
          nationality: 'American',
          notes: 'Former Goldman Sachs CEO; designed TARP bailout; allowed Lehman to fail',
        },
        {
          id: 'figure-2008-002',
          name: 'Ben Bernanke',
          role: 'Federal Reserve Chairman',
          organization: 'Federal Reserve',
          nationality: 'American',
          notes: 'Authorized unprecedented bailouts and quantitative easing',
        },
        {
          id: 'figure-2008-003',
          name: 'Timothy Geithner',
          role: 'NY Fed President / Treasury Secretary',
          organization: 'Federal Reserve / US Treasury',
          nationality: 'American',
          notes: 'Key architect of bailout; ensured AIG paid Goldman 100 cents on dollar',
        },
        {
          id: 'figure-2008-004',
          name: 'Lloyd Blankfein',
          role: 'CEO',
          organization: 'Goldman Sachs',
          nationality: 'American',
          notes: 'Oversaw Goldman during crisis; claimed doing "God\'s work"',
        },
      ],
      relatedTopics: ['topic-fed-001', 'topic-bis-001'],
      contradictions: [
        'Free market vs. bailouts for banks',
        'Moral hazard warnings vs. Too Big To Fail',
        'Criminal fraud vs. zero prosecutions',
        'Crisis prevention vs. larger banks post-crisis',
      ],
      unansweredQuestions: [
        'Why were no executives prosecuted?',
        'How much did insiders profit from crisis?',
        'Was Lehman sacrifice coordinated?',
        'What triggered the $550B electronic bank run?',
      ],
    },
    {
      id: 'topic-dynasty-001',
      name: 'Rothschild Banking Dynasty',
      description:
        'Investigation into the historical rise and continuing influence of the Rothschild banking family on global finance.',
      dateRange: {
        start: '1760',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'The Rothschilds were a successful banking family who pioneered international finance in the 19th century but whose influence has waned in the modern era.',
      alternativeTheories: [
        'Family controls major central banks indirectly',
        'Financed both sides of major wars',
        'Accumulated wealth far exceeds public estimates',
        'Media ownership suppresses coverage',
        'Intermarried with other banking dynasties',
        'Modern influence hidden through trusts and foundations',
      ],
      keyEvidence: [
        'Established banks in five European capitals simultaneously',
        'Courier network faster than governments',
        'Financed British war against Napoleon',
        'Waterloo advance knowledge trading documented',
        'Connected to Federal Reserve founding families',
        'Ownership stakes in major corporations obscured',
      ],
      documents: [
        {
          id: 'doc-dynasty-001',
          title: 'The House of Rothschild',
          type: 'investigative',
          source: 'Niall Ferguson',
          keyFindings: [
            'Unprecedented banking network creation',
            'Government financing across Europe',
            'Information advantage exploitation',
          ],
        },
        {
          id: 'doc-dynasty-002',
          title: 'British Parliamentary Records - Rothschild Loans',
          type: 'official',
          source: 'UK Parliament',
          keyFindings: [
            'Financing of British Empire documented',
            'Suez Canal purchase funded',
            'Multiple government bailouts provided',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-dynasty-001',
          name: 'Mayer Amschel Rothschild',
          role: 'Dynasty Founder',
          organization: 'M.A. Rothschild & Sons',
          nationality: 'German',
          notes: 'Founded dynasty in Frankfurt; sent five sons to establish European branches',
        },
        {
          id: 'figure-dynasty-002',
          name: 'Nathan Mayer Rothschild',
          role: 'London Branch Founder',
          organization: 'N.M. Rothschild & Sons',
          nationality: 'British',
          notes: 'Most powerful of five brothers; financed British government; Waterloo legend',
        },
        {
          id: 'figure-dynasty-003',
          name: 'Jacob Rothschild',
          role: 'Investment Trust Chairman',
          organization: 'RIT Capital Partners',
          nationality: 'British',
          notes: 'Modern family patriarch; extensive political and business connections',
        },
      ],
      relatedTopics: ['topic-fed-001', 'topic-bis-001'],
      contradictions: [
        'Diminished influence claims vs. continued asset growth',
        'Transparency vs. private family holdings',
        'Neutral bankers vs. war financing both sides',
        'Public service vs. profit from government debt',
      ],
      unansweredQuestions: [
        'What is the true extent of Rothschild wealth?',
        'How much central bank stock do they control?',
        'What political influence remains today?',
        'How are assets hidden across trusts and foundations?',
      ],
    },
  ],
  keyQuestions: [
    'Who controls the global monetary system?',
    'How do central banks coordinate policy through the BIS?',
    'What is the true cost of fiat currency since 1971?',
    'How does the petrodollar system shape foreign policy and wars?',
    'What would ending the Fed mean for the economy?',
    'How much influence do banking dynasties retain today?',
    'Was the 2008 crisis engineered for consolidation?',
    'What is the endgame for Central Bank Digital Currencies?',
    'How are financial crises used to expand central bank power?',
    'What role does the gold standard abolition play in wealth inequality?',
  ],
  motto: 'Follow the money to find the truth.',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2025-01-01'),
};

export default financialSystemsAgent;
