/**
 * Agent REMEDY - Medical Cover-ups & Pharmaceutical Industry Specialist
 * Investigates suppressed cures, pharmaceutical corruption, and medical establishment deception
 */

import { SourceType, SourceReliability } from '@ourstory/timeline-engine';
import {
  StoryAgent,
  AgentSpecialization,
  ResearchMethodology,
  InvestigationStatus,
} from '../types';

export const medicalCoverupsAgent: StoryAgent = {
  id: 'agent-remedy-010',
  name: 'Medical Cover-ups Research Agent',
  codename: 'REMEDY',
  description:
    'Specialized agent investigating pharmaceutical industry corruption, suppressed medical treatments, regulatory capture, and the profit-driven healthcare system. Analyzes patterns of silencing researchers, burying studies, and prioritizing profit over patient health. Examines historical and ongoing cases of medical fraud, suppressed cures, and the systematic marginalization of alternative treatments.',
  specialization: AgentSpecialization.MEDICAL_COVERUPS,
  methodologies: [
    ResearchMethodology.DOCUMENT_ANALYSIS,
    ResearchMethodology.PATTERN_RECOGNITION,
    ResearchMethodology.SOURCE_TRIANGULATION,
    ResearchMethodology.WITNESS_TESTIMONY,
    ResearchMethodology.NETWORK_MAPPING,
    ResearchMethodology.DECLASSIFICATION_TRACKING,
  ],
  primarySources: [
    SourceType.ACADEMIC,
    SourceType.ALTERNATIVE,
    SourceType.DECLASSIFIED,
  ],
  preferredReliability: [
    SourceReliability.PRIMARY,
    SourceReliability.SECONDARY,
    SourceReliability.CONTESTED,
  ],
  expertise: [
    'Pharmaceutical industry practices',
    'FDA regulatory capture',
    'Suppressed cancer treatments',
    'Vaccine injury compensation data',
    'Opioid epidemic origins',
    'Medical research fraud',
    'Natural remedy suppression',
    'Tuskegee and Guatemala experiments',
    'Industry whistleblowers',
    'Healthcare profit motives',
    'Clinical trial manipulation',
    'Off-label marketing fraud',
    'Generic drug suppression',
    'Patent evergreening tactics',
    'Medical journal corruption',
  ],
  researchTopics: [
    {
      id: 'topic-pharma-001',
      name: 'Pharmaceutical Industry Corruption',
      description:
        'Investigation into patterns of fraud, data manipulation, and regulatory capture in the pharmaceutical industry.',
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'The pharmaceutical industry is heavily regulated and provides safe, effective medications that improve public health.',
      alternativeTheories: [
        'Industry routinely buries negative study results',
        'Regulatory agencies captured by industry',
        'Profit motive overrides patient safety',
        'Revolving door between FDA and pharma',
        'Treatments are designed for profit, not cures',
        'Whistleblowers are systematically silenced',
      ],
      keyEvidence: [
        'Billions in fraud settlements paid annually',
        'Ghost-written studies common practice',
        'Negative studies buried in file drawers',
        'FDA officials join pharma after approval decisions',
        'Opioid crisis manufactured by industry',
        'Vioxx killed estimated 60,000 before withdrawal',
        'Clinical trial data often not published',
        'Pay-for-delay deals to block generics',
      ],
      documents: [
        {
          id: 'doc-pharma-001',
          title: 'Department of Justice Pharma Settlements',
          type: 'official',
          source: 'US Department of Justice',
          keyFindings: [
            'Billions in criminal and civil penalties',
            'Repeated violations by same companies',
            'Fraud includes marketing and safety data',
          ],
        },
        {
          id: 'doc-pharma-002',
          title: 'Vioxx Internal Documents',
          type: 'leaked',
          source: 'Court discovery',
          keyFindings: [
            'Merck knew of heart attack risk',
            'Data was manipulated in publications',
            'Marketing continued despite known dangers',
          ],
        },
        {
          id: 'doc-pharma-003',
          title: 'GlaxoSmithKline Fraud Settlement',
          type: 'official',
          releaseDate: '2012',
          source: 'US Department of Justice',
          keyFindings: [
            '$3 billion settlement - largest healthcare fraud at time',
            'Illegal marketing of Paxil for children',
            'Withholding safety data on Avandia',
            'Paid kickbacks to physicians',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-pharma-001',
          name: 'Peter Rost',
          role: 'Pfizer VP / Whistleblower',
          organization: 'Pfizer',
          nationality: 'Swedish-American',
          notes: 'Exposed illegal marketing practices; career destroyed',
        },
        {
          id: 'figure-pharma-002',
          name: 'Cheryl Eckard',
          role: 'Quality Assurance Manager / Whistleblower',
          organization: 'GlaxoSmithKline',
          nationality: 'American',
          notes: 'Exposed manufacturing fraud; received $96 million whistleblower award',
        },
        {
          id: 'figure-pharma-003',
          name: 'Dr. David Graham',
          role: 'FDA Safety Officer',
          organization: 'FDA',
          nationality: 'American',
          notes: 'Testified to Congress about Vioxx dangers; faced retaliation',
        },
        {
          id: 'figure-pharma-004',
          name: 'Dr. Marcia Angell',
          role: 'Former Editor-in-Chief',
          organization: 'New England Journal of Medicine',
          nationality: 'American',
          notes: 'Exposed pharmaceutical industry influence on medical research',
        },
      ],
      relatedTopics: ['topic-opioid-001', 'topic-suppressed-001', 'topic-vaccine-001'],
      contradictions: [
        'Patient safety claims vs. profit maximization behavior',
        'Heavy regulation claims vs. routine fraud findings',
        'Evidence-based medicine vs. buried studies',
        'Penalties paid vs. continued violations',
        'Public health mission vs. shareholder primacy',
      ],
      unansweredQuestions: [
        'How many deaths result from suppressed safety data?',
        'How deep is regulatory capture at the FDA?',
        'What treatments have been suppressed for profit?',
        'How can the system be reformed?',
        'Why do criminal executives avoid prison?',
      ],
    },
    {
      id: 'topic-opioid-001',
      name: 'Opioid Epidemic',
      description:
        'Investigation into how the pharmaceutical industry manufactured the opioid crisis through deceptive marketing and regulatory capture.',
      dateRange: {
        start: '1996',
        end: 'ongoing',
      },
      status: InvestigationStatus.PARTIALLY_RESOLVED,
      officialNarrative:
        'The opioid crisis resulted from overprescription and some misleading marketing that has since been addressed through settlements and regulatory changes.',
      alternativeTheories: [
        'Crisis was deliberately manufactured for profit',
        'Companies knew addiction risks and systematically lied',
        'Regulators were complicit through revolving door',
        'Sackler family escaped criminal accountability',
        'Distributors ignored obvious red flags intentionally',
        'System designed to create dependent customers',
        'McKinsey consulting role shows industry-wide conspiracy',
      ],
      keyEvidence: [
        'Internal documents show companies knew addiction risk from start',
        'OxyContin marketed as less addictive - proven false',
        'Sales reps incentivized for high-dose prescriptions',
        'Pill mills operated openly for years',
        'Distributors shipped millions of pills to small towns',
        '500,000+ Americans dead from overdoses since 1999',
        'Purdue Pharma bankruptcy structured to shield Sacklers',
        'FDA approved higher doses despite no evidence of safety',
        'McKinsey advised "turbocharging" sales amid crisis',
      ],
      documents: [
        {
          id: 'doc-opioid-001',
          title: 'Purdue Pharma Internal Documents',
          type: 'leaked',
          source: 'Court proceedings',
          keyFindings: [
            'Addiction risk was known and concealed since 1990s',
            'Marketing specifically targeted high prescribers',
            'Company tracked and encouraged escalating doses',
            'Sales tactics designed to overcome physician concerns',
          ],
        },
        {
          id: 'doc-opioid-002',
          title: 'McKinsey Consulting Documents',
          type: 'leaked',
          source: 'State AG investigations',
          releaseDate: '2021',
          keyFindings: [
            'Advised Purdue to "turbocharge" sales',
            'Strategies to counter DEA enforcement',
            'Proposed paying distributors rebates for overdose lawsuits',
          ],
        },
        {
          id: 'doc-opioid-003',
          title: 'DEA Distributor Reports',
          type: 'official',
          source: 'Drug Enforcement Administration',
          keyFindings: [
            'Millions of pills shipped to small pharmacies',
            'Suspicious orders ignored by distributors',
            'Enforcement actions delayed by lobbying',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-opioid-001',
          name: 'Sackler Family',
          role: 'Owners of Purdue Pharma',
          organization: 'Purdue Pharma',
          nationality: 'American',
          notes: 'Extracted billions while company faced lawsuits; no criminal charges',
        },
        {
          id: 'figure-opioid-002',
          name: 'Richard Sackler',
          role: 'President of Purdue Pharma',
          organization: 'Purdue Pharma',
          nationality: 'American',
          timeActive: '1999-2003',
          notes: 'Pushed aggressive sales tactics; blamed addicts for crisis',
        },
        {
          id: 'figure-opioid-003',
          name: 'Dr. Curtis Wright',
          role: 'FDA Medical Officer',
          organization: 'FDA / Purdue Pharma',
          nationality: 'American',
          notes: 'Approved OxyContin at FDA; joined Purdue within 2 years',
        },
        {
          id: 'figure-opioid-004',
          name: 'Joe Rannazzisi',
          role: 'DEA Deputy Assistant Administrator',
          organization: 'Drug Enforcement Administration',
          nationality: 'American',
          notes: 'Fought distributor lobby; pushed out after industry pressure',
        },
      ],
      relatedTopics: ['topic-pharma-001'],
      contradictions: [
        'Non-addictive claims vs. mass addiction epidemic',
        'Medical purpose vs. profit maximization',
        'Oversight claims vs. distributors shipping millions of pills',
        'Justice vs. bankruptcy protection for billionaires',
        'Public health priority vs. industry lobbying power',
      ],
      unansweredQuestions: [
        'Why has no Sackler family member gone to prison?',
        'How was this allowed to continue for over two decades?',
        'What is the true death toll including indirect deaths?',
        'How can victims receive meaningful justice?',
        'What role did FDA officials play in enabling the crisis?',
      ],
    },
    {
      id: 'topic-suppressed-001',
      name: 'Suppressed Cancer Treatments',
      description:
        'Investigation into alternative and suppressed cancer treatments that have been marginalized despite evidence of efficacy, including cases of researchers whose careers were destroyed.',
      dateRange: {
        start: '1920s',
        end: 'ongoing',
      },
      status: InvestigationStatus.COVERED_UP,
      officialNarrative:
        'Mainstream cancer treatments (chemotherapy, radiation, surgery) represent the only proven approaches. Alternative treatments lack scientific evidence and can be dangerous.',
      alternativeTheories: [
        'Effective alternative treatments have been systematically suppressed',
        'Cancer industry worth billions - cure would destroy profits',
        'Researchers with promising treatments have been persecuted',
        'FDA has been weaponized against alternative practitioners',
        'Chemotherapy efficacy vastly overstated',
        'Prevention research underfunded compared to treatment',
        'Natural compounds cannot be patented, so not pursued',
      ],
      keyEvidence: [
        'Royal Rife frequency therapy destroyed by AMA in 1930s',
        'Dr. Stanislaw Burzynski faced decades of FDA prosecution',
        'Laetrile (B17) banned despite patient testimonials',
        'Dr. Max Gerson therapy marginalized despite documented cases',
        'Harry Hoxsey clinics shut down; treatment now available in Mexico',
        'Essiac tea developer Rene Caisse harassed by authorities',
        'DCA (dichloroacetate) research underfunded - not patentable',
        'Cannabis research blocked for decades despite evidence',
      ],
      documents: [
        {
          id: 'doc-cancer-001',
          title: 'Burzynski FDA Investigation Files',
          type: 'official',
          source: 'FDA via FOIA',
          keyFindings: [
            'Multiple grand jury investigations failed to indict',
            'FDA spent millions prosecuting single doctor',
            'Patients testified treatment saved their lives',
            'Texas Medical Board attempted license revocation',
          ],
        },
        {
          id: 'doc-cancer-002',
          title: 'Rife Machine Historical Documentation',
          type: 'investigative',
          source: 'Various researchers',
          keyFindings: [
            'Laboratory destroyed under mysterious circumstances',
            'Scientific papers disappeared from libraries',
            'Colleagues who continued research faced persecution',
            'AMA involvement in suppression documented',
          ],
        },
        {
          id: 'doc-cancer-003',
          title: 'NCI Unconventional Cancer Treatments Report',
          type: 'official',
          releaseDate: '1990',
          source: 'Office of Technology Assessment',
          keyFindings: [
            'Acknowledged many alternatives never properly studied',
            'Bias in evaluation of non-conventional approaches',
            'Called for more open-minded investigation',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-cancer-001',
          name: 'Royal Raymond Rife',
          role: 'Inventor / Researcher',
          nationality: 'American',
          timeActive: '1920s-1950s',
          notes: 'Developed frequency therapy; lab destroyed, work suppressed',
        },
        {
          id: 'figure-cancer-002',
          name: 'Dr. Stanislaw Burzynski',
          role: 'Physician / Researcher',
          organization: 'Burzynski Clinic',
          nationality: 'Polish-American',
          notes: 'Antineoplaston therapy; decades of FDA prosecution',
        },
        {
          id: 'figure-cancer-003',
          name: 'Dr. Max Gerson',
          role: 'Physician',
          nationality: 'German-American',
          timeActive: '1930s-1959',
          notes: 'Nutritional therapy for cancer; marginalized by medical establishment',
        },
        {
          id: 'figure-cancer-004',
          name: 'Harry Hoxsey',
          role: 'Naturopath',
          nationality: 'American',
          timeActive: '1920s-1960s',
          notes: 'Herbal cancer treatment; clinics shut down by FDA',
        },
        {
          id: 'figure-cancer-005',
          name: 'Rene Caisse',
          role: 'Nurse',
          nationality: 'Canadian',
          timeActive: '1920s-1970s',
          notes: 'Essiac tea developer; faced government harassment',
        },
      ],
      relatedTopics: ['topic-pharma-001', 'topic-natural-001'],
      contradictions: [
        'War on cancer since 1971 vs. limited survival improvements',
        'Evidence-based medicine claims vs. refusal to study alternatives',
        'Patient choice rhetoric vs. prosecution of alternative practitioners',
        'Cancer research funding vs. prevention research neglect',
        'Precision medicine promise vs. continued reliance on toxic chemotherapy',
      ],
      unansweredQuestions: [
        'How many effective treatments have been suppressed?',
        'What role does patent law play in treatment development?',
        'Why are researchers with alternatives targeted?',
        'How can suppressed research be fairly evaluated?',
        'What is the true efficacy of conventional treatments?',
      ],
    },
    {
      id: 'topic-vaccine-001',
      name: 'Vaccine Injury and Compensation System',
      description:
        'Investigation into the National Vaccine Injury Compensation Program, documented vaccine injuries, and the 1986 liability shield for manufacturers.',
      dateRange: {
        start: '1986',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'Vaccines are safe and effective. The compensation program handles rare adverse events while ensuring vaccine availability. Manufacturers need liability protection to continue providing vaccines.',
      alternativeTheories: [
        'Liability shield removed incentive for safety improvements',
        'Compensation program designed to minimize payouts',
        'True injury rates vastly underreported',
        'VAERS data represents small fraction of actual injuries',
        'Conflicts of interest in safety oversight',
        'Whistleblower claims of data manipulation suppressed',
        'Informed consent inadequate for true risk disclosure',
      ],
      keyEvidence: [
        '$4.7+ billion paid in vaccine injury compensation since 1988',
        'Only 1% of adverse events estimated to be reported to VAERS',
        '1986 National Childhood Vaccine Injury Act removed liability',
        'HHS failed to file required safety reports for 30 years',
        'Simpsonwood CDC meeting transcripts show concerns',
        'Manufacturers cannot be sued for design defects',
        'Compensation claims take years, most denied',
        'Gardasil injuries documented across multiple countries',
      ],
      documents: [
        {
          id: 'doc-vaccine-001',
          title: 'HRSA Vaccine Injury Compensation Data',
          type: 'official',
          source: 'Health Resources and Services Administration',
          keyFindings: [
            'Billions paid to families of injured children',
            'Most common injuries include encephalopathy, seizures',
            'Average time to resolution exceeds 3 years',
          ],
        },
        {
          id: 'doc-vaccine-002',
          title: 'Simpsonwood Meeting Transcript',
          type: 'leaked',
          releaseDate: '2000',
          source: 'FOIA request',
          keyFindings: [
            'CDC convened secret meeting on thimerosal data',
            'Attendees expressed concern about findings',
            'Discussion of how to handle public relations',
          ],
        },
        {
          id: 'doc-vaccine-003',
          title: 'HHS OIG Audit on Safety Reporting',
          type: 'official',
          releaseDate: '2018',
          source: 'HHS Office of Inspector General',
          keyFindings: [
            'HHS failed to submit required biennial safety reports',
            '30+ years of non-compliance with 1986 Act mandate',
            'No safety report ever submitted to Congress as required',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-vaccine-001',
          name: 'Dr. William Thompson',
          role: 'CDC Senior Scientist',
          organization: 'Centers for Disease Control',
          nationality: 'American',
          notes: 'Alleged data manipulation in MMR study; granted whistleblower protection',
        },
        {
          id: 'figure-vaccine-002',
          name: 'Dr. Bernadine Healy',
          role: 'Former NIH Director',
          organization: 'National Institutes of Health',
          nationality: 'American',
          notes: 'Called for more vaccine safety research before her death',
        },
        {
          id: 'figure-vaccine-003',
          name: 'Robert F. Kennedy Jr.',
          role: 'Attorney / Activist',
          organization: "Children's Health Defense",
          nationality: 'American',
          notes: 'Prominent vaccine safety advocate; sued HHS over safety reports',
        },
        {
          id: 'figure-vaccine-004',
          name: 'Dr. Peter Aaby',
          role: 'Researcher',
          organization: 'Bandim Health Project',
          nationality: 'Danish',
          notes: 'Research on non-specific effects of vaccines; questioned DTP safety',
        },
      ],
      relatedTopics: ['topic-pharma-001', 'topic-tuskegee-001'],
      contradictions: [
        'Safe and effective claims vs. billions in injury payments',
        'Rare adverse events vs. underreporting estimates',
        'Informed consent vs. inadequate risk disclosure',
        'Safety studies vs. lack of inert placebo controls',
        'Public health priority vs. manufacturer liability shield',
      ],
      unansweredQuestions: [
        'What is the true rate of vaccine injuries?',
        'Why was manufacturer liability removed?',
        'Why has HHS never submitted required safety reports?',
        'How would vaccine development change with liability?',
        'What is the long-term safety profile of newer vaccines?',
      ],
    },
    {
      id: 'topic-natural-001',
      name: 'Natural Remedy Suppression',
      description:
        'Investigation into the systematic suppression of natural remedies, herbal medicines, and nutritional therapies by pharmaceutical and regulatory interests.',
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'Natural remedies lack scientific evidence and proper safety testing. Regulation is necessary to protect consumers from unproven and potentially dangerous treatments.',
      alternativeTheories: [
        'Natural substances cannot be patented, reducing profit incentive',
        'Codex Alimentarius designed to restrict supplement access',
        'FDA raids on supplement companies protect pharma interests',
        'Traditional medicine knowledge being deliberately lost',
        'Practitioners of natural medicine systematically persecuted',
        'Medical schools receive pharma funding, ignore nutrition',
        'Studies on natural remedies deliberately underfunded',
      ],
      keyEvidence: [
        'FDA raids on supplement companies like Life Extension',
        'Ephedra ban despite centuries of safe traditional use',
        'Cannabis prohibition blocked research for decades',
        'Vitamin C IV therapy practitioners targeted',
        'Raw milk producers subjected to armed raids',
        'DSHEA constantly under attack by pharma interests',
        'Codex harmonization threatens supplement access globally',
        'Medical education includes minimal nutrition training',
      ],
      documents: [
        {
          id: 'doc-natural-001',
          title: 'FDA Raid Documentation - Life Extension Foundation',
          type: 'investigative',
          source: 'Life Extension Foundation',
          keyFindings: [
            'Armed FDA raids on vitamin company',
            'Years of prosecution ultimately unsuccessful',
            'Products later approved as safe',
          ],
        },
        {
          id: 'doc-natural-002',
          title: 'Codex Alimentarius Guidelines',
          type: 'official',
          source: 'World Health Organization / FAO',
          keyFindings: [
            'International guidelines could restrict supplement access',
            'Industry influence on guideline development',
            'Harmonization pressure on national regulations',
          ],
        },
        {
          id: 'doc-natural-003',
          title: 'NIH Funding Analysis - Natural Products',
          type: 'academic',
          source: 'Various researchers',
          keyFindings: [
            'Minimal funding for natural product research',
            'Patent barriers prevent commercial development',
            'Bias toward patentable synthetic compounds',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-natural-001',
          name: 'Dr. Linus Pauling',
          role: 'Nobel Laureate / Researcher',
          nationality: 'American',
          timeActive: '1970s-1994',
          notes: 'Vitamin C research marginalized by medical establishment',
        },
        {
          id: 'figure-natural-002',
          name: 'Dr. Jonathan Wright',
          role: 'Physician',
          organization: 'Tahoma Clinic',
          nationality: 'American',
          notes: 'Natural medicine practitioner; clinic raided by FDA',
        },
        {
          id: 'figure-natural-003',
          name: 'Dr. Andrew Saul',
          role: 'Researcher / Educator',
          nationality: 'American',
          notes: 'Orthomolecular medicine advocate; promotes nutritional therapy',
        },
        {
          id: 'figure-natural-004',
          name: 'William Faloon',
          role: 'Founder',
          organization: 'Life Extension Foundation',
          nationality: 'American',
          notes: 'Fought FDA raids; advocate for supplement freedom',
        },
      ],
      relatedTopics: ['topic-suppressed-001', 'topic-pharma-001'],
      contradictions: [
        'Consumer protection claims vs. safe traditional remedy bans',
        'Evidence-based medicine vs. refusal to fund natural product studies',
        'Supplement safety vs. armed raids on vitamin companies',
        'Medical freedom vs. prosecution of alternative practitioners',
        'Integrative medicine lip service vs. marginalization in practice',
      ],
      unansweredQuestions: [
        'How many effective natural remedies have been suppressed?',
        'What is the role of patent law in treatment availability?',
        'How can traditional medicine knowledge be preserved?',
        'Why do regulators target natural remedy practitioners?',
        'What would healthcare look like with nutrition emphasis?',
      ],
    },
    {
      id: 'topic-tuskegee-001',
      name: 'Tuskegee Syphilis Study',
      description:
        'Investigation into the US government study that deliberately left Black men untreated for syphilis for 40 years, and its connection to broader patterns of medical experimentation on vulnerable populations.',
      dateRange: {
        start: '1932',
        end: '1972',
      },
      status: InvestigationStatus.DECLASSIFIED,
      officialNarrative:
        'The Tuskegee study was an unethical medical experiment that has been acknowledged and apologized for. It led to reforms in research ethics including the Belmont Report and IRBs.',
      alternativeTheories: [
        'Represents pattern of medical experimentation on minorities',
        'Similar experiments continued in Guatemala and elsewhere',
        'Distrust of medical establishment is historically justified',
        'Part of broader eugenics movement in American medicine',
        'Reform measures insufficient to prevent future abuses',
        'Experimental patterns continue with vulnerable populations',
      ],
      keyEvidence: [
        '600 Black men enrolled without informed consent',
        'Treatment withheld even after penicillin widely available',
        'Study continued for 40 years until exposed by press',
        'Men told they were receiving treatment (deception)',
        'Exposed by whistleblower Peter Buxtun, not self-correction',
        'Guatemala experiments involved intentional infection',
        'Prison experiments continued for decades',
        'Henrietta Lacks cells taken without consent',
      ],
      documents: [
        {
          id: 'doc-tusk-001',
          title: 'CDC Tuskegee Study Documentation',
          type: 'official',
          source: 'Centers for Disease Control',
          keyFindings: [
            '40 years of deceptive experimentation',
            'Subjects denied available treatment',
            'Deaths resulted from deliberate medical neglect',
          ],
        },
        {
          id: 'doc-tusk-002',
          title: 'Presidential Commission Guatemala Report',
          type: 'official',
          releaseDate: '2011',
          source: 'Presidential Commission for the Study of Bioethical Issues',
          keyFindings: [
            'US government intentionally infected Guatemalans with STDs',
            'Experiments conducted 1946-1948',
            'Included prisoners, mental patients, soldiers',
            'Obama formally apologized in 2010',
          ],
        },
        {
          id: 'doc-tusk-003',
          title: 'Belmont Report',
          type: 'official',
          releaseDate: '1979',
          source: 'National Commission for Protection of Human Subjects',
          keyFindings: [
            'Established ethical principles for research',
            'Created in response to Tuskegee exposure',
            'Foundation for modern research ethics',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-tusk-001',
          name: 'Peter Buxtun',
          role: 'PHS Investigator / Whistleblower',
          organization: 'Public Health Service',
          nationality: 'American',
          notes: 'Exposed the study after internal complaints ignored for years',
        },
        {
          id: 'figure-tusk-002',
          name: 'Dr. John Cutler',
          role: 'Lead Researcher',
          organization: 'Public Health Service',
          nationality: 'American',
          notes: 'Led both Tuskegee and Guatemala experiments',
        },
        {
          id: 'figure-tusk-003',
          name: 'Eunice Rivers',
          role: 'Public Health Nurse',
          organization: 'Public Health Service',
          nationality: 'American',
          notes: 'Maintained contact with subjects throughout study',
        },
        {
          id: 'figure-tusk-004',
          name: 'Henrietta Lacks',
          role: 'Patient',
          nationality: 'American',
          timeActive: '1951',
          notes: 'Cells taken without consent; became HeLa cell line',
        },
      ],
      relatedTopics: ['topic-pharma-001', 'topic-vaccine-001'],
      contradictions: [
        'Do no harm oath vs. deliberate harm infliction',
        'Informed consent principle vs. systematic deception',
        'Public health mission vs. exploitation of vulnerable populations',
        'Isolated incident claims vs. pattern of abuse',
        'Ethics reform claims vs. continued vulnerable population targeting',
      ],
      unansweredQuestions: [
        'What other unethical experiments remain undisclosed?',
        'How can medical trust be rebuilt in affected communities?',
        'What accountability existed for perpetrators?',
        'Are current safeguards sufficient to prevent future abuses?',
        'What experiments were conducted that remain classified?',
      ],
    },
  ],
  keyQuestions: [
    'How corrupt is the pharmaceutical industry?',
    'What treatments have been suppressed for profit?',
    'How captured are regulatory agencies by industry?',
    'What is the true cost of profit-driven medicine?',
    'How can healthcare be reformed to prioritize patients over profits?',
  ],
  motto: 'Health should never be hostage to profit.',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export default medicalCoverupsAgent;
