/**
 * Agent GRASSY KNOLL - Political Assassinations Research Specialist
 * Investigates JFK, RFK, MLK, and other suspicious deaths of political figures
 */

import { SourceType, SourceReliability } from '@ourstory/timeline-engine';
import {
  StoryAgent,
  AgentSpecialization,
  ResearchMethodology,
  InvestigationStatus,
} from '../types';

export const politicalAssassinationsAgent: StoryAgent = {
  id: 'agent-grassyknoll-008',
  name: 'Political Assassinations Research Agent',
  codename: 'GRASSY KNOLL',
  description:
    'Specialized agent investigating political assassinations, suspicious deaths of public figures, and the cover-ups surrounding them. Focuses on the Kennedy assassinations, MLK, and patterns of eliminating voices that threaten established power structures.',
  specialization: AgentSpecialization.POLITICAL_ASSASSINATIONS,
  methodologies: [
    ResearchMethodology.FORENSIC_ANALYSIS,
    ResearchMethodology.WITNESS_TESTIMONY,
    ResearchMethodology.DOCUMENT_ANALYSIS,
    ResearchMethodology.TIMELINE_RECONSTRUCTION,
    ResearchMethodology.PATTERN_RECOGNITION,
  ],
  primarySources: [SourceType.DECLASSIFIED, SourceType.ACADEMIC, SourceType.ALTERNATIVE],
  preferredReliability: [
    SourceReliability.PRIMARY,
    SourceReliability.SECONDARY,
    SourceReliability.CONTESTED,
  ],
  expertise: [
    'JFK assassination',
    'RFK assassination',
    'MLK assassination',
    'Malcolm X assassination',
    'Warren Commission',
    'HSCA investigation',
    'CIA involvement allegations',
    'FBI COINTELPRO',
    'Mafia connections',
    'Witness deaths',
    'Ballistic evidence',
    'Zapruder film analysis',
    'Suspicious journalist deaths',
    'Whistleblower deaths',
    'Political witness elimination',
  ],
  researchTopics: [
    {
      id: 'topic-jfk-001',
      name: 'JFK Assassination',
      description:
        'Investigation into the assassination of President John F. Kennedy in Dallas on November 22, 1963.',
      dateRange: {
        start: '1963-11-22',
        end: '1963-11-22',
      },
      status: InvestigationStatus.COVERED_UP,
      officialNarrative:
        'Lee Harvey Oswald acted alone, firing three shots from the Texas School Book Depository, killing President Kennedy.',
      alternativeTheories: [
        'Multiple shooters were involved',
        'CIA orchestrated the assassination',
        'Mafia involvement with CIA cooperation',
        'Military-industrial complex motive',
        'Anti-Castro Cubans participated',
        'Oswald was a patsy as he claimed',
        'LBJ involvement',
      ],
      keyEvidence: [
        'Magic bullet theory contradicts physics',
        'Zapruder film shows backward head movement',
        'Witnesses reported shots from grassy knoll',
        'Acoustic evidence suggested multiple shooters',
        'Oswald killed before trial',
        'Jack Ruby had mob connections',
        'JFK threatened to splinter CIA',
        'Signed EO 11110 challenging Federal Reserve',
        'Wanted to withdraw from Vietnam',
      ],
      documents: [
        {
          id: 'doc-jfk-001',
          title: 'Warren Commission Report',
          type: 'official',
          releaseDate: '1964',
          source: 'Warren Commission',
          keyFindings: [
            'Oswald acted alone',
            'Single bullet theory',
            'No conspiracy found',
          ],
        },
        {
          id: 'doc-jfk-002',
          title: 'HSCA Final Report',
          type: 'official',
          releaseDate: '1979',
          source: 'House Select Committee on Assassinations',
          keyFindings: [
            'Probable conspiracy',
            'Acoustic evidence of second shooter',
            'Criticized Warren Commission',
          ],
        },
        {
          id: 'doc-jfk-003',
          title: 'JFK Records Collection',
          type: 'declassified',
          source: 'National Archives',
          keyFindings: [
            'Many documents still withheld',
            'CIA operational interest in Oswald',
            'FBI prior knowledge concealed',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-jfk-001',
          name: 'Lee Harvey Oswald',
          role: 'Alleged assassin',
          nationality: 'American',
          notes: 'Killed by Jack Ruby before trial; claimed he was a patsy',
        },
        {
          id: 'figure-jfk-002',
          name: 'Jack Ruby',
          role: 'Nightclub owner / Oswald\'s killer',
          nationality: 'American',
          notes: 'Had mob connections; died of cancer before retrial',
        },
        {
          id: 'figure-jfk-003',
          name: 'Allen Dulles',
          role: 'Former CIA Director',
          organization: 'CIA / Warren Commission',
          nationality: 'American',
          notes: 'Fired by JFK; appointed to Warren Commission',
        },
      ],
      relatedTopics: ['topic-rfk-001', 'topic-mlk-001'],
      contradictions: [
        'Lone gunman vs. multiple shooter evidence',
        'Magic bullet vs. physics',
        'Case closed vs. documents still classified',
        'No conspiracy vs. HSCA finding probable conspiracy',
      ],
      unansweredQuestions: [
        'Why are documents still classified 60 years later?',
        'What was Oswald\'s relationship with intelligence agencies?',
        'Who benefited from JFK\'s death?',
        'Why was Oswald killed before he could talk?',
        'What did witnesses see on the grassy knoll?',
      ],
    },
    {
      id: 'topic-rfk-001',
      name: 'RFK Assassination',
      description:
        'Investigation into the assassination of Robert F. Kennedy on June 5, 1968, in Los Angeles.',
      dateRange: {
        start: '1968-06-05',
        end: '1968-06-05',
      },
      status: InvestigationStatus.COVERED_UP,
      officialNarrative:
        'Sirhan Sirhan acted alone, shooting RFK in the Ambassador Hotel kitchen.',
      alternativeTheories: [
        'Second shooter was present',
        'Sirhan was a Manchurian candidate',
        'CIA involvement through MK-Ultra',
        'Security guard Thane Eugene Cesar was shooter',
        'Sirhan cannot remember the shooting',
      ],
      keyEvidence: [
        'More bullet holes than Sirhan\'s gun capacity',
        'Fatal shot from behind; Sirhan was in front',
        'Powder burns indicate point-blank range',
        'Sirhan has no memory of shooting',
        'Hypnotic programming evidence',
        'Security guard drew weapon, was behind RFK',
        'LAPD destroyed evidence',
      ],
      documents: [
        {
          id: 'doc-rfk-001',
          title: 'LAPD Investigation Files',
          type: 'official',
          source: 'Los Angeles Police Department',
          keyFindings: [
            'Evidence destroyed',
            'Extra bullets not explained',
            'Witness testimony conflicts',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-rfk-001',
          name: 'Sirhan Sirhan',
          role: 'Convicted assassin',
          nationality: 'Palestinian-Jordanian',
          notes: 'Claims no memory of shooting; denied parole repeatedly',
        },
        {
          id: 'figure-rfk-002',
          name: 'Thane Eugene Cesar',
          role: 'Security guard',
          organization: 'Ace Guard Service',
          nationality: 'American',
          notes: 'Was directly behind RFK; drew weapon; later sold gun',
        },
      ],
      relatedTopics: ['topic-jfk-001', 'topic-mkultra-001'],
      contradictions: [
        'Sirhan in front vs. fatal shot from behind',
        '8 bullets fired vs. more holes found',
        'Case closed vs. evidence destroyed',
        'Voluntary act vs. no memory of event',
      ],
      unansweredQuestions: [
        'How was Sirhan programmed?',
        'Who fired the fatal shot from behind?',
        'Why was evidence destroyed?',
        'What is the connection to MK-Ultra?',
      ],
    },
    {
      id: 'topic-mlk-001',
      name: 'MLK Assassination',
      description:
        'Investigation into the assassination of Dr. Martin Luther King Jr. on April 4, 1968, in Memphis, Tennessee. FBI\'s COINTELPRO targeted him; a 1999 civil trial found government agencies liable.',
      dateRange: {
        start: '1968-04-04',
        end: '1968-04-04',
      },
      status: InvestigationStatus.COVERED_UP,
      officialNarrative:
        'James Earl Ray acted alone, shooting Dr. King from a rooming house bathroom across the street from the Lorraine Motel.',
      alternativeTheories: [
        'FBI orchestrated the assassination through COINTELPRO',
        'James Earl Ray was a patsy',
        'Military intelligence involvement',
        'Memphis Police complicity',
        'Organized crime connection',
        'Government conspiracy proven in 1999 civil trial',
      ],
      keyEvidence: [
        'FBI\'s COINTELPRO targeted MLK as "most dangerous Negro"',
        'FBI sent anonymous letters urging MLK to commit suicide',
        'Ray recanted confession, claimed he was set up',
        '1999 King family civil trial found government liable',
        'Jowers testimony about conspiracy',
        'Witnesses reported shooter in bushes, not rooming house',
        'Ballistic evidence contested',
        'Ray had mysterious funding for international travel',
        'Police and military surveillance withdrawn day of shooting',
      ],
      documents: [
        {
          id: 'doc-mlk-001',
          title: 'FBI COINTELPRO Files',
          type: 'declassified',
          source: 'FBI',
          keyFindings: [
            'MLK targeted for neutralization',
            'Surveillance and harassment campaigns',
            'Suicide letter sent to MLK',
          ],
        },
        {
          id: 'doc-mlk-002',
          title: 'King vs. Jowers Civil Trial Verdict',
          type: 'official',
          releaseDate: '1999',
          source: 'Shelby County Circuit Court',
          keyFindings: [
            'Conspiracy involving government agencies',
            'Jowers was part of the plot',
            'Lloyd Jowers liable for wrongful death',
          ],
        },
        {
          id: 'doc-mlk-003',
          title: 'HSCA MLK Investigation',
          type: 'official',
          releaseDate: '1979',
          source: 'House Select Committee on Assassinations',
          keyFindings: [
            'Likelihood of conspiracy',
            'Possible involvement of others',
            'Ray likely not sole perpetrator',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-mlk-001',
          name: 'James Earl Ray',
          role: 'Convicted assassin',
          nationality: 'American',
          notes: 'Recanted confession; claimed he was set up by man named "Raoul"; died in prison seeking new trial',
        },
        {
          id: 'figure-mlk-002',
          name: 'J. Edgar Hoover',
          role: 'FBI Director',
          organization: 'FBI',
          nationality: 'American',
          notes: 'Authorized COINTELPRO targeting MLK; called him "most dangerous Negro in America"',
        },
        {
          id: 'figure-mlk-003',
          name: 'Lloyd Jowers',
          role: 'Restaurant owner',
          nationality: 'American',
          notes: 'Confessed to involvement; found liable in 1999 civil trial; claimed he was asked to hire hitman',
        },
      ],
      relatedTopics: ['topic-jfk-001', 'topic-rfk-001', 'topic-malcolm-x-001'],
      contradictions: [
        'Lone gunman vs. civil trial conspiracy finding',
        'Ray\'s confession vs. recantation',
        'Official investigation vs. 1999 trial verdict',
        'Bathroom shot vs. witness reports of bushes',
      ],
      unansweredQuestions: [
        'Who was the mysterious "Raoul" Ray claimed set him up?',
        'Why did the King family believe government was responsible?',
        'What was the full extent of FBI involvement?',
        'Why was military intelligence in Memphis that day?',
      ],
    },
    {
      id: 'topic-malcolm-x-001',
      name: 'Malcolm X Assassination',
      description:
        'Investigation into the assassination of Malcolm X on February 21, 1965, at the Audubon Ballroom in New York City. In 2021, two men convicted were exonerated after evidence of FBI/NYPD misconduct emerged.',
      dateRange: {
        start: '1965-02-21',
        end: '1965-02-21',
      },
      status: InvestigationStatus.PARTIALLY_RESOLVED,
      officialNarrative:
        'Three members of the Nation of Islam shot Malcolm X during a speaking engagement. Talmadge Hayer, Norman Butler, and Thomas Johnson were convicted.',
      alternativeTheories: [
        'FBI COINTELPRO orchestrated the assassination',
        'NYPD complicity and cover-up',
        'Nation of Islam used as patsies',
        'Government wanted to silence growing influence',
        'Two of three convicted men were innocent',
      ],
      keyEvidence: [
        '2021 exoneration of Muhammad Aziz and Khalil Islam',
        'FBI informant was Malcolm X\'s bodyguard',
        'NYPD withdrew security detail before shooting',
        'FBI documents showed surveillance and interference',
        'COINTELPRO targeted Black nationalist movements',
        'Withheld evidence proving innocence',
        'Only Hayer admitted guilt; others maintained innocence for 55 years',
      ],
      documents: [
        {
          id: 'doc-malcolm-001',
          title: 'Manhattan DA Investigation Report',
          type: 'official',
          releaseDate: '2021',
          source: 'Manhattan District Attorney',
          keyFindings: [
            'FBI and NYPD withheld evidence',
            'Two convictions were wrongful',
            'Investigation was corrupted',
          ],
        },
        {
          id: 'doc-malcolm-002',
          title: 'FBI COINTELPRO Files - Black Nationalist',
          type: 'declassified',
          source: 'FBI',
          keyFindings: [
            'Malcolm X under surveillance',
            'Efforts to create division',
            'Informant placed in his security',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-malcolm-001',
          name: 'Talmadge Hayer (Thomas Hagan)',
          role: 'Admitted shooter',
          nationality: 'American',
          notes: 'Only person who admitted guilt; stated the other two convicted were not present',
        },
        {
          id: 'figure-malcolm-002',
          name: 'Muhammad Aziz (Norman Butler)',
          role: 'Wrongfully convicted',
          nationality: 'American',
          notes: 'Exonerated in 2021 after 55 years; was not present at shooting',
        },
        {
          id: 'figure-malcolm-003',
          name: 'Khalil Islam (Thomas Johnson)',
          role: 'Wrongfully convicted',
          nationality: 'American',
          notes: 'Exonerated posthumously in 2021; maintained innocence until death',
        },
      ],
      relatedTopics: ['topic-mlk-001', 'topic-jfk-001'],
      contradictions: [
        'Three men convicted vs. only one admitted guilt',
        'Thorough investigation vs. withheld evidence',
        'Case closed vs. 2021 exonerations',
        'Nation of Islam acted alone vs. FBI/NYPD complicity',
      ],
      unansweredQuestions: [
        'Who were the other actual shooters?',
        'What was the full extent of FBI involvement?',
        'Why was security removed before the assassination?',
        'Who ordered the cover-up of exculpatory evidence?',
      ],
    },
    {
      id: 'topic-suspicious-deaths-001',
      name: 'Suspicious Deaths of Witnesses & Journalists',
      description:
        'Investigation into the pattern of suspicious deaths of journalists, witnesses, and whistleblowers who were investigating powerful interests or had testimony threatening to official narratives.',
      dateRange: {
        start: '1965-11-08',
        end: '2004-12-10',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'These deaths were suicides, accidents, or natural causes with no connection to the individuals\' investigative work.',
      alternativeTheories: [
        'Systematic elimination of inconvenient witnesses',
        'Pattern indicates organized silencing',
        'Intelligence agency involvement',
        'Deaths conveniently timed before testimony or publication',
        'Threat to power structures triggered elimination',
      ],
      keyEvidence: [
        'Dorothy Kilgallen died before publishing JFK book; notes disappeared',
        'Gary Webb "suicide" with two gunshots to head',
        'Karen Silkwood died before meeting with NYT reporter with documents',
        'Danny Casolaro "suicide" before exposing Inslaw/Octopus conspiracy',
        'DC Madam Deborah Palfrey "suicide" before trial',
        'Over 100 JFK witnesses died within years of assassination',
        'Statistical improbability of witness death rates',
        'Michael Hastings car explosion before story on CIA director',
      ],
      documents: [
        {
          id: 'doc-deaths-001',
          title: 'JFK Witness Deaths Study',
          type: 'academic',
          source: 'Various researchers',
          keyFindings: [
            'Actuarial odds of witness deaths astronomical',
            'Pattern of deaths before testimony',
            'Unusual causes of death',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-deaths-001',
          name: 'Dorothy Kilgallen',
          role: 'Journalist',
          nationality: 'American',
          notes: 'Died November 8, 1965; was investigating JFK assassination; interviewed Jack Ruby; notes and manuscript disappeared',
        },
        {
          id: 'figure-deaths-002',
          name: 'Gary Webb',
          role: 'Investigative journalist',
          nationality: 'American',
          notes: 'Died December 10, 2004; exposed CIA-Contra-cocaine connection; ruled "suicide" with TWO gunshots to head',
        },
        {
          id: 'figure-deaths-003',
          name: 'Karen Silkwood',
          role: 'Nuclear whistleblower',
          nationality: 'American',
          notes: 'Died November 13, 1974; car accident en route to meet NYT with documents about safety violations; documents never found',
        },
        {
          id: 'figure-deaths-004',
          name: 'Danny Casolaro',
          role: 'Investigative journalist',
          nationality: 'American',
          notes: 'Died August 10, 1991; "suicide" in hotel while investigating Inslaw/PROMIS software scandal; warned friends "if I die it\'s not suicide"',
        },
        {
          id: 'figure-deaths-005',
          name: 'Michael Hastings',
          role: 'Journalist',
          nationality: 'American',
          notes: 'Died June 18, 2013; car exploded at high speed; was working on story about CIA director; told colleagues he was being investigated',
        },
        {
          id: 'figure-deaths-006',
          name: 'Deborah Palfrey',
          role: 'DC Madam',
          nationality: 'American',
          notes: 'Died May 1, 2008; "suicide" before trial; had told media she would never kill herself; client list included powerful DC figures',
        },
      ],
      relatedTopics: ['topic-jfk-001', 'topic-rfk-001'],
      contradictions: [
        'Suicide ruling vs. two gunshots to head (Gary Webb)',
        'Accident vs. missing documents (Silkwood)',
        'Random deaths vs. statistical pattern',
        'No foul play vs. victims\' warnings about their safety',
      ],
      unansweredQuestions: [
        'What is the statistical probability of these death rates?',
        'Where are the missing documents and notes?',
        'Why were investigations quickly closed?',
        'How many more cases remain uninvestigated?',
        'Is there a coordinated program for eliminating witnesses?',
      ],
    },
    {
      id: 'topic-fred-hampton-001',
      name: 'Fred Hampton Assassination',
      description:
        'Investigation into the FBI-orchestrated raid that killed Black Panther leader Fred Hampton on December 4, 1969. Declassified documents proved FBI COINTELPRO coordinated with Chicago police.',
      dateRange: {
        start: '1969-12-04',
        end: '1969-12-04',
      },
      status: InvestigationStatus.DECLASSIFIED,
      officialNarrative:
        'Chicago Police conducted a legitimate raid and were met with gunfire; officers acted in self-defense.',
      alternativeTheories: [
        'FBI planned assassination through COINTELPRO',
        'Hampton was drugged before raid',
        'Police fired 99 shots, Panthers fired 1',
        'Premeditated murder, not a raid',
        'Informant provided floor plan for targeted killing',
      ],
      keyEvidence: [
        'FBI informant William O\'Neal provided apartment floor plan',
        'O\'Neal drugged Hampton\'s drink before raid',
        'Police fired 99 shots; Panthers fired only 1',
        'Hampton was shot in bed, likely unconscious',
        'FBI documents show COINTELPRO neutralization order',
        '$1.85 million settlement to families in 1982',
        'Civil trial revealed FBI coordination',
      ],
      documents: [
        {
          id: 'doc-hampton-001',
          title: 'COINTELPRO - Black Panther Party Files',
          type: 'declassified',
          source: 'FBI',
          keyFindings: [
            'Hampton identified for "neutralization"',
            'O\'Neal was FBI informant',
            'Floor plan provided to raiders',
          ],
        },
        {
          id: 'doc-hampton-002',
          title: 'Civil Lawsuit Settlement',
          type: 'official',
          releaseDate: '1982',
          source: 'Federal Court',
          keyFindings: [
            'FBI, Chicago Police, Cook County liable',
            '$1.85 million settlement',
            'Acknowledged wrongful deaths',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-hampton-001',
          name: 'Fred Hampton',
          role: 'Black Panther Chairman',
          nationality: 'American',
          notes: 'Killed at age 21; was building multiracial coalition; FBI considered him major threat',
        },
        {
          id: 'figure-hampton-002',
          name: 'William O\'Neal',
          role: 'FBI informant',
          nationality: 'American',
          notes: 'Infiltrated Panthers; provided floor plan; drugged Hampton; later admitted role; died in 1990',
        },
        {
          id: 'figure-hampton-003',
          name: 'Mark Clark',
          role: 'Black Panther leader',
          nationality: 'American',
          notes: 'Also killed in the raid; his was the only Panther shot fired (likely reflexive upon death)',
        },
      ],
      relatedTopics: ['topic-mlk-001', 'topic-malcolm-x-001'],
      contradictions: [
        'Shootout vs. 99-1 shot ratio',
        'Self-defense vs. Hampton shot in bed',
        'Legitimate raid vs. COINTELPRO assassination',
        'Investigation closed vs. $1.85M settlement',
      ],
      unansweredQuestions: [
        'Who gave the final order for the raid?',
        'Why has no one been criminally prosecuted?',
        'How many other COINTELPRO assassinations occurred?',
      ],
    },
  ],
  keyQuestions: [
    'Why are Kennedy assassination documents still classified?',
    'What is the pattern of eliminating reform candidates?',
    'How many assassinations involved intelligence agencies?',
    'What happened to key witnesses?',
    'How does mind control factor into assassinations?',
    'What was COINTELPRO\'s role in assassinating Black leaders?',
    'Why were journalists investigating these cases killed?',
    'How many wrongful convictions concealed the real perpetrators?',
    'What is the statistical probability of witness death rates?',
  ],
  motto: 'The bullets tell a different story than the official record.',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-11-23'),
};

export default politicalAssassinationsAgent;
