/**
 * Agent ILLUMINATE - Secret Societies & Hidden Power Structures Specialist
 * Investigates Illuminati, Freemasonry, Bilderberg, Skull and Bones, and elite networks
 *
 * DEPLOYMENT: ILLUMINATE - Secret Societies Deep Investigation
 * Coverage: Bilderberg, Skull and Bones, CFR, Trilateral Commission, Bohemian Grove, Freemasonry
 */

import { SourceType, SourceReliability } from '@ourstory/timeline-engine';
import {
  StoryAgent,
  AgentSpecialization,
  ResearchMethodology,
  InvestigationStatus,
} from '../types';

export const secretSocietiesAgent: StoryAgent = {
  id: 'agent-illuminate-006',
  name: 'Secret Societies Research Agent',
  codename: 'ILLUMINATE',
  description:
    'Elite research agent specializing in secret societies, hidden power structures, and interlocking networks of global influence. Investigates the Bilderberg Group, Skull and Bones, Council on Foreign Relations, Trilateral Commission, Bohemian Grove, Freemasonry, and the historical Bavarian Illuminati. Maps connections between elite organizations and their influence on geopolitical events, financial systems, and the selection of world leaders.',
  specialization: AgentSpecialization.SECRET_SOCIETIES,
  methodologies: [
    ResearchMethodology.NETWORK_MAPPING,
    ResearchMethodology.DOCUMENT_ANALYSIS,
    ResearchMethodology.PATTERN_RECOGNITION,
    ResearchMethodology.TIMELINE_RECONSTRUCTION,
    ResearchMethodology.SOURCE_TRIANGULATION,
    ResearchMethodology.DECLASSIFICATION_TRACKING,
  ],
  primarySources: [SourceType.ACADEMIC, SourceType.ALTERNATIVE, SourceType.DECLASSIFIED],
  preferredReliability: [
    SourceReliability.PRIMARY,
    SourceReliability.SECONDARY,
    SourceReliability.CONTESTED,
  ],
  expertise: [
    'Bavarian Illuminati history and dissolution',
    'Freemasonry structure, degrees, and historical influence',
    'Skull and Bones recruitment and power networks',
    'Bilderberg Group meetings and attendee analysis',
    'Council on Foreign Relations policy influence',
    'Trilateral Commission global coordination',
    'Bohemian Grove rituals and membership',
    'Elite bloodline connections',
    'Occult symbolism in power structures',
    'New World Order agenda research',
    'Rhodes Scholarship network',
    'Club of Rome influence',
    'World Economic Forum / Davos connections',
    'Interlocking board directorships',
    'Central banking family networks',
  ],
  researchTopics: [
    {
      id: 'topic-bilderberg-001',
      name: 'Bilderberg Group',
      description:
        'Comprehensive investigation into the annual invitation-only conference of approximately 120-150 political leaders, corporate executives, central bankers, and media titans. Founded in 1954 at the Hotel de Bilderberg in the Netherlands, these meetings have shaped transatlantic policy for seven decades.',
      dateRange: {
        start: '1954',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'Bilderberg is a private forum for informal, off-the-record discussion about major issues facing the world. No resolutions are proposed, no votes are taken, and no policy statements are issued.',
      alternativeTheories: [
        'Bilderberg meetings coordinate global policy across nations before public debates',
        'Attendees are vetted and groomed for leadership positions',
        'The euro and EU integration were discussed at Bilderberg years before public awareness',
        'Media blackout is enforced despite major owners being attendees',
        'Decisions at Bilderberg precede major geopolitical shifts',
        'The group represents a shadow government above elected officials',
        'Bilderberg is connected to the creation of the European Union',
      ],
      keyEvidence: [
        'Founded by Prince Bernhard of the Netherlands (former Nazi Party member)',
        'Original funding came from CIA through front organizations',
        'Strict security and police protection at every meeting location',
        'Attendees include sitting presidents, prime ministers, royalty, and central bankers',
        'Media executives attend but provide virtually no coverage',
        'Chatham House Rule prevents attribution of any statements',
        'EU formation discussed at 1955 Garmisch-Partenkirchen meeting',
        'Tony Blair attended 1993 meeting before becoming PM in 1997',
        'Bill Clinton attended 1991 meeting before 1992 presidential run',
        'Angela Merkel attended before becoming Chancellor',
        'Emmanuel Macron attended before French presidency',
        'No minutes or records officially released',
        'Dutch police confirmed orders to protect Bilderberg come from highest levels',
      ],
      documents: [
        {
          id: 'doc-bild-001',
          title: 'Bilderberg Meeting Participant Lists (1954-present)',
          type: 'leaked',
          source: 'Various whistleblowers and investigative journalists',
          keyFindings: [
            'Heads of state and government regularly attend',
            'Central bankers from Federal Reserve, ECB, Bank of England',
            'CEOs of major tech, oil, and finance companies',
            'Media owners: Washington Post, The Economist, Financial Times',
          ],
        },
        {
          id: 'doc-bild-002',
          title: 'The True Story of the Bilderberg Group',
          type: 'investigative',
          source: 'Daniel Estulin',
          releaseDate: '2005',
          keyFindings: [
            'Documented connections between Bilderberg decisions and subsequent policy',
            'Mapped the network of recurring attendees',
            'Traced funding sources to intelligence agencies',
          ],
        },
        {
          id: 'doc-bild-003',
          title: 'BBC Documentary on Bilderberg',
          type: 'official',
          source: 'BBC',
          releaseDate: '2003',
          keyFindings: [
            'Confirmed existence and secrecy of meetings',
            'Interviewed former attendees who confirmed policy discussions',
            'Documented security arrangements',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-bild-001',
          name: 'David Rockefeller',
          role: 'Steering Committee member (1954-2017)',
          organization: 'Chase Manhattan Bank / Rockefeller Foundation',
          nationality: 'American',
          timeActive: '1954-2017',
          notes:
            'Attended virtually every Bilderberg meeting for 60+ years. Also founded the Trilateral Commission. In his memoirs, wrote: "Some even believe we are part of a secret cabal working against the best interests of the United States... If that is the charge, I stand guilty, and I am proud of it."',
        },
        {
          id: 'figure-bild-002',
          name: 'Henry Kissinger',
          role: 'Regular attendee and Steering Committee',
          organization: 'US State Department / Kissinger Associates',
          nationality: 'American',
          timeActive: '1957-present',
          notes:
            'Key figure in multiple elite organizations including CFR, Trilateral Commission. Attended Bilderberg before becoming National Security Advisor and Secretary of State.',
        },
        {
          id: 'figure-bild-003',
          name: 'Prince Bernhard of the Netherlands',
          role: 'Co-founder and first chairman',
          organization: 'Dutch Royal Family',
          nationality: 'Dutch',
          timeActive: '1954-1976',
          notes:
            'Former member of Nazi Party and SS. Founded Bilderberg with Polish exile Józef Retinger. Resigned after Lockheed bribery scandal.',
        },
        {
          id: 'figure-bild-004',
          name: 'Étienne Davignon',
          role: 'Chairman of Bilderberg Steering Committee',
          organization: 'European Commission',
          nationality: 'Belgian',
          timeActive: '1999-2011',
          notes:
            'Former Vice-President of European Commission. Admitted in interviews that Bilderberg helped create the euro.',
        },
      ],
      relatedTopics: ['topic-cfr-001', 'topic-trilateral-001', 'topic-skull-001', 'topic-davos-001'],
      contradictions: [
        'Claims of no policy influence vs. attendees consistently rising to power afterward',
        'Private discussion vs. police-state level security',
        'Open democratic society vs. complete media blackout',
        'No votes taken vs. policy convergence among member nations',
        'Transparency advocacy by attendees vs. absolute secrecy of proceedings',
        'Free press vs. media owners attending but not reporting',
      ],
      unansweredQuestions: [
        'What specific policies have been coordinated at Bilderberg meetings?',
        'How exactly are attendees selected and by whom?',
        'What is discussed in the classified sessions?',
        'Why has no attendee ever broken the secrecy oath?',
        'What is the relationship between Bilderberg and intelligence agencies?',
        'How do Bilderberg decisions influence EU, NATO, and UN policy?',
      ],
    },
    {
      id: 'topic-skull-001',
      name: 'Skull and Bones',
      description:
        'Deep investigation into Yale University\'s oldest and most powerful secret society, Order 322. Founded in 1832 by William Huntington Russell after visiting Germany, the society has produced three presidents, numerous CIA directors, Supreme Court justices, cabinet members, and titans of industry. Only 15 seniors are "tapped" each year.',
      dateRange: {
        start: '1832',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'Skull and Bones is simply a college fraternity with quirky traditions and famous alumni, but holds no special influence over American society.',
      alternativeTheories: [
        'Skull and Bones serves as a recruitment pipeline for intelligence services',
        'Members are systematically placed in key positions across government, media, and finance',
        'The "322" refers to the founding of the order in Demosthenes\' death year (322 BCE)',
        'Rituals involve mock sacrifices and oaths of absolute loyalty',
        'The society was modeled on German Illuminati structures',
        'Members use their network to advance each other regardless of merit',
        'The order controls access to the highest levels of American power',
        'Bonesmen have coordinated major historical events including wars',
      ],
      keyEvidence: [
        'Three US Presidents were members: Taft (1878), Bush Sr. (1948), Bush Jr. (1968)',
        '2004 presidential election: both candidates (Bush and Kerry) were Bonesmen',
        'When asked about Bones on Meet the Press, both candidates refused to discuss it',
        'CIA founders and early directors were members (e.g., George H.W. Bush)',
        'Percy Rockefeller, Averell Harriman, and other dynasty figures were members',
        'William F. Buckley Jr. (member) founded modern conservative movement',
        'Members have controlled major media outlets including Time magazine',
        'The "Tomb" headquarters on Yale campus remains completely secret',
        'Initiation rituals reportedly include lying in a coffin and revealing sexual secrets',
        'Members are required to leave the room if Skull and Bones is mentioned by non-members',
        'Society funded by Russell Trust Association, an opaque financial entity',
        'Prescott Bush allegedly stole Geronimo\'s skull for the Tomb',
      ],
      documents: [
        {
          id: 'doc-skull-001',
          title: "America's Secret Establishment: An Introduction to the Order of Skull & Bones",
          type: 'investigative',
          source: 'Antony Sutton',
          releaseDate: '1983',
          keyFindings: [
            'Documented member career trajectories over 150 years',
            'Mapped interlocking relationships between members',
            'Traced policy influence across administrations',
            'Connected to Hegelian philosophy of controlled dialectic',
          ],
        },
        {
          id: 'doc-skull-002',
          title: 'Secrets of the Tomb: Skull and Bones, the Ivy League, and the Hidden Paths of Power',
          type: 'investigative',
          source: 'Alexandra Robbins (former Yale)',
          releaseDate: '2002',
          keyFindings: [
            'Detailed initiation ritual descriptions from sources',
            'Documented the "crooking" practice of networking',
            'Interviewed multiple members and their families',
          ],
        },
        {
          id: 'doc-skull-003',
          title: 'The Tomb Interior Photographs',
          type: 'leaked',
          source: 'Anonymous insider, 2000s',
          keyFindings: [
            'Photos show occult imagery and human skulls',
            'Nazi memorabilia reportedly present',
            'Room dedicated to German origins',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-skull-001',
          name: 'William Huntington Russell',
          role: 'Co-founder',
          organization: 'Russell Trust Association',
          nationality: 'American',
          timeActive: '1832-1885',
          notes:
            'Founded Skull and Bones after returning from Germany. Family involved in opium trade with China.',
        },
        {
          id: 'figure-skull-002',
          name: 'George H.W. Bush',
          role: '41st President / CIA Director / Bonesman (1948)',
          organization: 'US Government / CIA',
          nationality: 'American',
          timeActive: '1948-2018',
          notes:
            'Tapped in 1948. Became CIA Director, Vice President, and President. Father and son both Bonesmen and Presidents.',
        },
        {
          id: 'figure-skull-003',
          name: 'Prescott Bush',
          role: 'Senator / Bonesman / Banker',
          organization: 'Brown Brothers Harriman',
          nationality: 'American',
          timeActive: '1917-1972',
          notes:
            'Father of George H.W. Bush. Banking activities with Fritz Thyssen (Hitler financier) led to assets being seized under Trading with the Enemy Act in 1942.',
        },
        {
          id: 'figure-skull-004',
          name: 'William F. Buckley Jr.',
          role: 'Media figure / CIA officer / Bonesman (1950)',
          organization: 'National Review / CIA',
          nationality: 'American',
          timeActive: '1950-2008',
          notes:
            'Founded National Review and shaped American conservatism. Admitted CIA service in Mexico. Used media platform to influence political discourse.',
        },
        {
          id: 'figure-skull-005',
          name: 'John Kerry',
          role: 'Secretary of State / Senator / Bonesman (1966)',
          organization: 'US Government',
          nationality: 'American',
          timeActive: '1966-present',
          notes:
            'Ran against fellow Bonesman George W. Bush in 2004. Refused to discuss Skull and Bones during campaign.',
        },
      ],
      relatedTopics: ['topic-bilderberg-001', 'topic-cfr-001', 'topic-illuminati-001'],
      contradictions: [
        'Just a college club vs. three presidents and countless power brokers',
        'No special influence vs. disproportionate representation in government',
        'Meritocracy vs. secret society advancement',
        'Open democracy vs. members who won\'t discuss membership',
        'Rule of law vs. members above accountability',
        'Free press vs. media controlled by members',
      ],
      unansweredQuestions: [
        'What specific oaths do members take upon initiation?',
        'How do members coordinate after graduation?',
        'What is the significance of "322" in the society name?',
        'What role did Bones play in CIA formation and operations?',
        'Why did both 2004 candidates refuse to discuss their membership?',
        'What artifacts are actually kept in the Tomb?',
        'How has the society influenced US foreign policy?',
      ],
    },
    {
      id: 'topic-cfr-001',
      name: 'Council on Foreign Relations',
      description:
        'Investigation into America\'s most influential foreign policy think tank, founded in 1921. The CFR has been called the "shadow government" due to its overwhelming influence on US foreign policy across all administrations regardless of party.',
      dateRange: {
        start: '1921',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'The CFR is a nonpartisan think tank and publisher that provides analysis on foreign policy issues and serves as a resource for its members, government officials, and the public.',
      alternativeTheories: [
        'CFR members dominate every presidential administration since WWII',
        'The organization sets US foreign policy regardless of elected leaders',
        'CFR promotes globalist agenda over American national interests',
        'Major media outlets are controlled by CFR members',
        'The CFR was designed to integrate the US into a world government',
        'CFR coordinates with Bilderberg and Trilateral Commission as interlocking organizations',
      ],
      keyEvidence: [
        'Founded by "The Inquiry" group that advised Woodrow Wilson at Paris Peace Conference',
        'Initial funding from Rockefeller and Carnegie foundations',
        'Every Secretary of State since 1944 has been a CFR member',
        'Virtually every CIA Director has been a CFR member',
        'Owns and operates Foreign Affairs, the most influential policy journal',
        'Members include presidents, cabinet officials, and Supreme Court justices',
        'Located at Harold Pratt House, Manhattan (Rockefeller-donated building)',
        'Membership limited to ~5,000 and by invitation only',
        'Admiral Chester Ward (member 20 years) called it "a school for one-world government"',
        'Hillary Clinton admitted taking direction from CFR in 2009 speech',
      ],
      documents: [
        {
          id: 'doc-cfr-001',
          title: 'War and Peace Studies Project Records',
          type: 'declassified',
          source: 'Council on Foreign Relations / State Department',
          releaseDate: 'Various',
          keyFindings: [
            'CFR planned post-WWII world order with State Department funding',
            'Designed United Nations structure',
            'Created blueprint for Bretton Woods system',
          ],
        },
        {
          id: 'doc-cfr-002',
          title: 'Annual Reports and Member Lists',
          type: 'official',
          source: 'Council on Foreign Relations',
          keyFindings: [
            'Documents cabinet-level saturation across administrations',
            'Shows media executives and anchors as members',
            'Reveals corporate CEO participation',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-cfr-001',
          name: 'John J. McCloy',
          role: 'Chairman (1953-1970)',
          organization: 'CFR / Chase Manhattan / World Bank',
          nationality: 'American',
          timeActive: '1940s-1989',
          notes:
            'Called "Chairman of the American Establishment." High Commissioner of Germany, World Bank President, Warren Commission member, Chase Manhattan Chairman. The ultimate power broker.',
        },
        {
          id: 'figure-cfr-002',
          name: 'Allen Dulles',
          role: 'President / CIA Director',
          organization: 'CFR / CIA / Sullivan & Cromwell',
          nationality: 'American',
          timeActive: '1927-1969',
          notes:
            'CFR President, then CIA Director. Fired by JFK after Bay of Pigs, then placed on Warren Commission investigating JFK assassination.',
        },
        {
          id: 'figure-cfr-003',
          name: 'Richard Haass',
          role: 'President (2003-2023)',
          organization: 'Council on Foreign Relations',
          nationality: 'American',
          timeActive: '2003-2023',
          notes:
            'Former State Department official. Longest-serving CFR president. Regular media commentator on foreign policy.',
        },
      ],
      relatedTopics: ['topic-bilderberg-001', 'topic-trilateral-001', 'topic-skull-001'],
      contradictions: [
        'Nonpartisan vs. promoting consistent globalist agenda',
        'Advisory role vs. members filling every major position',
        'Independent analysis vs. setting actual policy',
        'Democratic governance vs. permanent unelected influence',
        'National interest vs. international integration',
      ],
      unansweredQuestions: [
        'How are members selected and what are the criteria?',
        'What happens in closed-door study groups?',
        'How do CFR recommendations become policy so consistently?',
        'What is the relationship between CFR, Bilderberg, and Trilateral Commission?',
        'Why do all administrations rely on CFR members regardless of campaign promises?',
      ],
    },
    {
      id: 'topic-trilateral-001',
      name: 'Trilateral Commission',
      description:
        'Investigation into the elite organization founded in 1973 by David Rockefeller and Zbigniew Brzezinski to foster closer cooperation between North America, Europe, and Japan (later expanded to Asia-Pacific).',
      dateRange: {
        start: '1973',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'The Trilateral Commission is a non-governmental discussion group that promotes dialogue between these three democratic industrialized regions on common challenges.',
      alternativeTheories: [
        'Created to manage the decline of US hegemony and transition to global governance',
        'Coordinates economic policy across major economies',
        'Jimmy Carter was selected and promoted by the Commission',
        'Represents the "management committee" of global capitalism',
        'Works to erode national sovereignty in favor of regional/global institutions',
        'Commission members drove NAFTA, WTO, and other trade frameworks',
      ],
      keyEvidence: [
        'Founded by David Rockefeller after Bilderberg proved insufficient for including Japan',
        'Zbigniew Brzezinski was first director, later became Carter\'s National Security Advisor',
        'Jimmy Carter was an unknown Georgia governor before Trilateral membership',
        'Carter filled cabinet with Trilateral members after 1976 election',
        'Commission published "Crisis of Democracy" (1975) suggesting too much democracy is problematic',
        'George H.W. Bush, Bill Clinton were members before becoming presidents',
        'Approximately 350-400 elite members from all three regions',
        'Members must resign upon entering government (officially)',
      ],
      documents: [
        {
          id: 'doc-tri-001',
          title: 'The Crisis of Democracy: Report on the Governability of Democracies',
          type: 'official',
          source: 'Trilateral Commission',
          releaseDate: '1975',
          keyFindings: [
            'Argued that democratic societies were becoming "ungovernable"',
            'Suggested that "excess of democracy" was the problem',
            'Proposed limiting democratic participation for governability',
            'Written by Crozier, Huntington, and Watanuki',
          ],
        },
        {
          id: 'doc-tri-002',
          title: 'Trilateral Commission Task Force Reports',
          type: 'official',
          source: 'Trilateral Commission',
          keyFindings: [
            'Advocated for free trade agreements years before NAFTA',
            'Promoted central bank independence from democratic oversight',
            'Supported European monetary integration',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-tri-001',
          name: 'David Rockefeller',
          role: 'Founder and Honorary Chairman',
          organization: 'Chase Manhattan Bank / Rockefeller Foundation',
          nationality: 'American',
          timeActive: '1973-2017',
          notes:
            'Founded Trilateral Commission in 1973, served as North American Chairman. Also key Bilderberg member. Most powerful banker of the 20th century.',
        },
        {
          id: 'figure-tri-002',
          name: 'Zbigniew Brzezinski',
          role: 'Co-founder and First Director',
          organization: 'National Security Council',
          nationality: 'American (Polish-born)',
          timeActive: '1973-2017',
          notes:
            'Columbia professor who co-founded Commission. Became Jimmy Carter\'s National Security Advisor. Architect of US support for Afghan mujahideen.',
        },
        {
          id: 'figure-tri-003',
          name: 'Jimmy Carter',
          role: '39th President / Commission member',
          organization: 'US Government',
          nationality: 'American',
          timeActive: '1973-1980',
          notes:
            'Unknown Georgia governor recruited to Commission in 1973. Elected president in 1976. Filled cabinet with 26 Trilateral Commission members.',
        },
      ],
      relatedTopics: ['topic-bilderberg-001', 'topic-cfr-001', 'topic-davos-001'],
      contradictions: [
        'Democratic values vs. "Crisis of Democracy" report',
        'Non-governmental vs. members becoming government officials',
        'Regional cooperation vs. global governance agenda',
        'Resignation upon government entry vs. continued coordination',
        'Free discussion vs. predetermined policy outcomes',
      ],
      unansweredQuestions: [
        'How was Jimmy Carter selected and promoted from obscurity?',
        'What specific policies have been coordinated across the three regions?',
        'How do the Commission, CFR, and Bilderberg divide responsibilities?',
        'Why did the Commission argue democracy was excessive?',
        'What role did the Commission play in creating the WTO and NAFTA?',
      ],
    },
    {
      id: 'topic-bohemian-001',
      name: 'Bohemian Grove',
      description:
        'Investigation into the exclusive 2,700-acre campground in Monte Rio, California, where the world\'s most powerful men gather annually for a two-week encampment featuring the "Cremation of Care" ritual.',
      dateRange: {
        start: '1878',
        end: 'ongoing',
      },
      status: InvestigationStatus.ONGOING,
      officialNarrative:
        'Bohemian Grove is a private campground owned by the Bohemian Club of San Francisco where members gather for theatrical performances, music, and fellowship away from the pressures of the world.',
      alternativeTheories: [
        'The Grove is where major policy decisions are made in informal settings',
        'The Manhattan Project was conceived at Bohemian Grove',
        '"Cremation of Care" is an occult ritual with deeper significance',
        'The all-male encampment involves ritualistic behavior',
        'Major business deals and political alliances are forged at the Grove',
        'The 40-foot owl statue represents Moloch or other occult deity',
        'Grove gatherings coordinate Republican political strategy',
      ],
      keyEvidence: [
        'Membership includes presidents, cabinet officials, CEOs, media figures',
        'Richard Nixon on tape: "It\'s the most faggy goddamn thing you could ever imagine"',
        'Manhattan Project scientists, including Edward Teller, discussed bomb at Grove (1942)',
        'Ronald Reagan and Nixon reportedly resolved their rivalry at the Grove',
        'Alex Jones secretly filmed "Cremation of Care" ritual in 2000',
        'Ritual involves mock human sacrifice before giant owl statue',
        'Membership list reads like Forbes 500 and political who\'s who',
        'Strict no-women policy maintained since founding',
        'Camps are named and have hierarchical prestige (Mandalay, Hillbillies, etc.)',
        'Henry Kissinger, George Shultz, Colin Powell confirmed attendees',
      ],
      documents: [
        {
          id: 'doc-grove-001',
          title: 'Bohemian Grove Membership Roster (Leaked)',
          type: 'leaked',
          source: 'Various',
          keyFindings: [
            'Presidents: Nixon, Reagan, both Bushes, etc.',
            'Secretaries of State, Defense, Treasury',
            'Major CEOs: Bechtel, oil companies, banks',
            'Media figures and university presidents',
          ],
        },
        {
          id: 'doc-grove-002',
          title: 'Dark Secrets: Inside Bohemian Grove (Documentary)',
          type: 'investigative',
          source: 'Alex Jones / InfoWars',
          releaseDate: '2000',
          keyFindings: [
            'Footage of "Cremation of Care" ceremony',
            'Giant owl statue documented',
            'Mock sacrifice ritual recorded',
          ],
        },
        {
          id: 'doc-grove-003',
          title: 'Philip Weiss Spy Magazine Investigation',
          type: 'investigative',
          source: 'Spy Magazine',
          releaseDate: '1989',
          keyFindings: [
            'Journalist infiltrated Grove as worker',
            'Documented attendees and activities',
            'Described lakeside talks and informal gatherings',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-grove-001',
          name: 'Richard Nixon',
          role: '37th President / Member',
          organization: 'US Government',
          nationality: 'American',
          timeActive: '1950s-1994',
          notes:
            'Long-time member. Gave famous "Lakeside Talk" in 1967 that helped launch 1968 presidential campaign. His taped comments reveal true nature of gatherings.',
        },
        {
          id: 'figure-grove-002',
          name: 'Henry Kissinger',
          role: 'Secretary of State / Regular attendee',
          organization: 'US Government / Kissinger Associates',
          nationality: 'American',
          timeActive: '1970s-present',
          notes:
            'Regular speaker and attendee. Connects Bohemian Grove to Bilderberg and CFR networks.',
        },
        {
          id: 'figure-grove-003',
          name: 'George Shultz',
          role: 'Secretary of State / Member',
          organization: 'US Government / Bechtel',
          nationality: 'American',
          timeActive: '1970s-2021',
          notes:
            'Bechtel executive and Reagan cabinet member. Key connector between corporate and political power at the Grove.',
        },
      ],
      relatedTopics: ['topic-skull-001', 'topic-bilderberg-001', 'topic-cfr-001'],
      contradictions: [
        'Mere fellowship vs. Manhattan Project conception',
        'Just entertainment vs. policy-shaping "Lakeside Talks"',
        'Relaxation retreat vs. occult-style rituals',
        'No business vs. attendees who run major corporations',
        'Private club vs. site of political deal-making',
        'Democracy vs. decisions made at secret retreats',
      ],
      unansweredQuestions: [
        'What is the true meaning of the "Cremation of Care" ritual?',
        'What significant decisions have been made at the Grove?',
        'Why the strict secrecy and security?',
        'What is discussed in the "Lakeside Talks"?',
        'How do Grove networks intersect with other elite organizations?',
        'What is the significance of the owl symbolism?',
      ],
    },
    {
      id: 'topic-illuminati-001',
      name: 'Bavarian Illuminati & Freemasonry',
      description:
        'Historical investigation into the Order of the Illuminati founded in 1776 by Adam Weishaupt, its infiltration of Freemasonry, supposed suppression in 1785, and alleged continuation through other organizations.',
      dateRange: {
        start: '1776',
        end: 'ongoing',
      },
      status: InvestigationStatus.COVERED_UP,
      officialNarrative:
        'The Bavarian Illuminati was a short-lived Enlightenment-era secret society that was effectively destroyed by government bans in 1785. Modern "Illuminati" references are baseless conspiracy theories.',
      alternativeTheories: [
        'The Illuminati successfully infiltrated Freemasonry before being "banned"',
        'The suppression was staged and the order continued underground',
        'Illuminati ideology drove the French Revolution',
        'The order\'s structure and goals were adopted by subsequent secret societies',
        'Modern globalist organizations are Illuminati successors',
        'The founding of America (1776) and Illuminati (1776) connected',
        'Illuminati symbolism appears on US dollar bill (eye and pyramid)',
      ],
      keyEvidence: [
        'Weishaupt founded order on May 1, 1776 (later celebrated as May Day)',
        'Original documents seized by Bavarian government in 1786 reveal conspiracy aims',
        'Documents showed plans to infiltrate governments, churches, Masonic lodges',
        'Members included notable figures: Goethe, Duke of Saxe-Gotha, Baron von Knigge',
        'Weishaupt fled to Gotha where he was protected until death (1830)',
        'French Revolution occurred shortly after Illuminati "dissolution"',
        'Great Seal of United States features pyramid with all-seeing eye',
        'Freemasonry spread rapidly after Illuminati infiltration',
        'Many Founding Fathers were Freemasons (Washington, Franklin, etc.)',
        'Rhodes Scholarship founded to spread similar ideology globally',
      ],
      documents: [
        {
          id: 'doc-illum-001',
          title: 'Einige Originalschriften des Illuminatenordens',
          type: 'official',
          source: 'Bavarian Government Seizure',
          releaseDate: '1787',
          keyFindings: [
            'Internal correspondence revealing structure and goals',
            'Plans for infiltrating Masonic lodges',
            'Strategies for placing members in positions of influence',
          ],
        },
        {
          id: 'doc-illum-002',
          title: 'Proofs of a Conspiracy',
          type: 'academic',
          source: 'John Robison (Edinburgh professor)',
          releaseDate: '1797',
          keyFindings: [
            'Documented Illuminati infiltration of Continental Freemasonry',
            'Connected order to French Revolution',
            'Warning to English-speaking world',
          ],
        },
        {
          id: 'doc-illum-003',
          title: 'Memoirs Illustrating the History of Jacobinism',
          type: 'academic',
          source: 'Augustin Barruel',
          releaseDate: '1797',
          keyFindings: [
            'Four-volume study of Illuminati and revolution',
            'Traced philosophical roots to Voltaire and Enlightenment',
            'Documented three-part conspiracy theory',
          ],
        },
      ],
      keyFigures: [
        {
          id: 'figure-illum-001',
          name: 'Adam Weishaupt',
          role: 'Founder of the Illuminati',
          organization: 'Order of the Illuminati / University of Ingolstadt',
          nationality: 'Bavarian',
          timeActive: '1776-1830',
          notes:
            'Jesuit-educated professor who founded the order at age 28. Lived in exile under protection of Duke of Saxe-Gotha until death. Wrote extensively defending the order.',
        },
        {
          id: 'figure-illum-002',
          name: 'Baron Adolph von Knigge',
          role: 'Recruiter and organizer',
          organization: 'Order of the Illuminati / Freemasonry',
          nationality: 'German',
          timeActive: '1780-1796',
          notes:
            'High-ranking Freemason who joined Illuminati and rapidly expanded membership. Created the ritual structure. Later left after disputes with Weishaupt.',
        },
        {
          id: 'figure-illum-003',
          name: 'Johann Wolfgang von Goethe',
          role: 'Member (Illuminatus minor)',
          organization: 'Order of the Illuminati',
          nationality: 'German',
          timeActive: '1783-1785',
          notes:
            'Germany\'s greatest literary figure was recruited as "Abaris." Reflected Illuminati themes in later works including Faust.',
        },
        {
          id: 'figure-illum-004',
          name: 'Albert Pike',
          role: 'Sovereign Grand Commander, Scottish Rite',
          organization: 'Freemasonry',
          nationality: 'American',
          timeActive: '1859-1891',
          notes:
            'Rewrote Scottish Rite rituals. Wrote "Morals and Dogma." Alleged to have corresponded with Giuseppe Mazzini about three world wars (disputed).',
        },
      ],
      relatedTopics: ['topic-skull-001', 'topic-bilderberg-001', 'topic-cfr-001'],
      contradictions: [
        'Suppressed in 1785 vs. founder protected until 1830',
        'Destroyed vs. ideology spread more widely afterward',
        'Historical curiosity vs. ongoing influence theories',
        'Enlightenment rationalism vs. occult ritual practices',
        'Secret society vs. published defenses and manifestos',
      ],
      unansweredQuestions: [
        'Did the Illuminati truly dissolve or merely go underground?',
        'What is the connection between Illuminati and modern secret societies?',
        'Why does their symbolism appear on US currency?',
        'How did Illuminati ideology influence subsequent revolutions?',
        'What was the relationship between Weishaupt and the Rothschild family?',
        'Are modern groups like Skull and Bones modeled on Illuminati structure?',
      ],
    },
  ],
  keyQuestions: [
    'How do interlocking elite networks (Bilderberg, CFR, Trilateral) coordinate global policy?',
    'What is the relationship between secret societies and intelligence agencies?',
    'How are world leaders selected and promoted through these networks?',
    'What is the ultimate agenda of interconnected elite organizations?',
    'How do these groups maintain secrecy across generations?',
    'What role do occult rituals play in elite bonding and loyalty?',
    'How has the internet era affected the ability to maintain secrecy?',
    'Are these organizations symptoms of natural elite coordination or something more orchestrated?',
  ],
  motto: 'In the shadows, power reveals its true form.',
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2025-01-23'),
};

export default secretSocietiesAgent;
